/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using DocuSign.eSign.Api;
using NUnit.Framework;

namespace DocuSign.eSign.Test.Api
{
    /// <summary>
    ///  Class for testing ContactsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ContactsApiTests
    {
        private ContactsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ContactsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ContactsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ContactsApi
            //Assert.IsInstanceOfType(typeof(ContactsApi), instance, "instance is a ContactsApi");
        }

        
        /// <summary>
        /// Test ContactsDeleteContactWithId
        /// </summary>
        [Test]
        public void ContactsDeleteContactWithIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string contactId = null;
            //var response = instance.ContactsDeleteContactWithId(accountId, contactId);
            //Assert.IsInstanceOf<ContactUpdateResponse> (response, "response is ContactUpdateResponse");
        }
        
        /// <summary>
        /// Test ContactsDeleteContacts
        /// </summary>
        [Test]
        public void ContactsDeleteContactsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //ContactModRequest contactModRequest = null;
            //var response = instance.ContactsDeleteContacts(accountId, contactModRequest);
            //Assert.IsInstanceOf<ContactUpdateResponse> (response, "response is ContactUpdateResponse");
        }
        
        /// <summary>
        /// Test ContactsGetContactById
        /// </summary>
        [Test]
        public void ContactsGetContactByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string contactId = null;
            //string cloudProvider = null;
            //var response = instance.ContactsGetContactById(accountId, contactId, cloudProvider);
            //Assert.IsInstanceOf<ContactGetResponse> (response, "response is ContactGetResponse");
        }
        
        /// <summary>
        /// Test ContactsPostContacts
        /// </summary>
        [Test]
        public void ContactsPostContactsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //ContactModRequest contactModRequest = null;
            //var response = instance.ContactsPostContacts(accountId, contactModRequest);
            //Assert.IsInstanceOf<ContactUpdateResponse> (response, "response is ContactUpdateResponse");
        }
        
        /// <summary>
        /// Test ContactsPutContacts
        /// </summary>
        [Test]
        public void ContactsPutContactsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //ContactModRequest contactModRequest = null;
            //var response = instance.ContactsPutContacts(accountId, contactModRequest);
            //Assert.IsInstanceOf<ContactUpdateResponse> (response, "response is ContactUpdateResponse");
        }
        
    }

}
