/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using DocuSign.eSign.Api;
using NUnit.Framework;

namespace DocuSign.eSign.Test.Api
{
    /// <summary>
    ///  Class for testing EnvelopeEmailSettingsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class EnvelopeEmailSettingsApiTests
    {
        private EnvelopeEmailSettingsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new EnvelopeEmailSettingsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EnvelopeEmailSettingsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EnvelopeEmailSettingsApi
            //Assert.IsInstanceOfType(typeof(EnvelopeEmailSettingsApi), instance, "instance is a EnvelopeEmailSettingsApi");
        }

        
        /// <summary>
        /// Test EmailSettingsDeleteEmailSettings
        /// </summary>
        [Test]
        public void EmailSettingsDeleteEmailSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //var response = instance.EmailSettingsDeleteEmailSettings(accountId, envelopeId);
            //Assert.IsInstanceOf<EnvelopeEmailSettings> (response, "response is EnvelopeEmailSettings");
        }
        
        /// <summary>
        /// Test EmailSettingsGetEmailSettings
        /// </summary>
        [Test]
        public void EmailSettingsGetEmailSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //var response = instance.EmailSettingsGetEmailSettings(accountId, envelopeId);
            //Assert.IsInstanceOf<EnvelopeEmailSettings> (response, "response is EnvelopeEmailSettings");
        }
        
        /// <summary>
        /// Test EmailSettingsPostEmailSettings
        /// </summary>
        [Test]
        public void EmailSettingsPostEmailSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //EnvelopeEmailSettings envelopeEmailSettings = null;
            //var response = instance.EmailSettingsPostEmailSettings(accountId, envelopeId, envelopeEmailSettings);
            //Assert.IsInstanceOf<EnvelopeEmailSettings> (response, "response is EnvelopeEmailSettings");
        }
        
        /// <summary>
        /// Test EmailSettingsPutEmailSettings
        /// </summary>
        [Test]
        public void EmailSettingsPutEmailSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //EnvelopeEmailSettings envelopeEmailSettings = null;
            //var response = instance.EmailSettingsPutEmailSettings(accountId, envelopeId, envelopeEmailSettings);
            //Assert.IsInstanceOf<EnvelopeEmailSettings> (response, "response is EnvelopeEmailSettings");
        }
        
    }

}
