/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using DocuSign.eSign.Api;
using NUnit.Framework;

namespace DocuSign.eSign.Test.Api
{
    /// <summary>
    ///  Class for testing EnvelopeViewsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class EnvelopeViewsApiTests
    {
        private EnvelopeViewsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new EnvelopeViewsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EnvelopeViewsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EnvelopeViewsApi
            //Assert.IsInstanceOfType(typeof(EnvelopeViewsApi), instance, "instance is a EnvelopeViewsApi");
        }

        
        /// <summary>
        /// Test ViewsPostAccountConsoleView
        /// </summary>
        [Test]
        public void ViewsPostAccountConsoleViewTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //ConsoleViewRequest consoleViewRequest = null;
            //var response = instance.ViewsPostAccountConsoleView(accountId, consoleViewRequest);
            //Assert.IsInstanceOf<EnvelopeViews> (response, "response is EnvelopeViews");
        }
        
        /// <summary>
        /// Test ViewsPostEnvelopeCorrectView
        /// </summary>
        [Test]
        public void ViewsPostEnvelopeCorrectViewTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //CorrectViewRequest correctViewRequest = null;
            //var response = instance.ViewsPostEnvelopeCorrectView(accountId, envelopeId, correctViewRequest);
            //Assert.IsInstanceOf<EnvelopeViews> (response, "response is EnvelopeViews");
        }
        
        /// <summary>
        /// Test ViewsPostEnvelopeEditView
        /// </summary>
        [Test]
        public void ViewsPostEnvelopeEditViewTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //ReturnUrlRequest returnUrlRequest = null;
            //var response = instance.ViewsPostEnvelopeEditView(accountId, envelopeId, returnUrlRequest);
            //Assert.IsInstanceOf<EnvelopeViews> (response, "response is EnvelopeViews");
        }
        
        /// <summary>
        /// Test ViewsPostEnvelopeRecipientView
        /// </summary>
        [Test]
        public void ViewsPostEnvelopeRecipientViewTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //RecipientViewRequest recipientViewRequest = null;
            //var response = instance.ViewsPostEnvelopeRecipientView(accountId, envelopeId, recipientViewRequest);
            //Assert.IsInstanceOf<EnvelopeViews> (response, "response is EnvelopeViews");
        }
        
        /// <summary>
        /// Test ViewsPostEnvelopeSenderView
        /// </summary>
        [Test]
        public void ViewsPostEnvelopeSenderViewTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //ReturnUrlRequest returnUrlRequest = null;
            //var response = instance.ViewsPostEnvelopeSenderView(accountId, envelopeId, returnUrlRequest);
            //Assert.IsInstanceOf<EnvelopeViews> (response, "response is EnvelopeViews");
        }
        
    }

}
