/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using DocuSign.eSign.Api;
using NUnit.Framework;

namespace DocuSign.eSign.Test.Api
{
    /// <summary>
    ///  Class for testing EnvelopeLocksApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class EnvelopeLocksApiTests
    {
        private EnvelopeLocksApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new EnvelopeLocksApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EnvelopeLocksApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EnvelopeLocksApi
            //Assert.IsInstanceOfType(typeof(EnvelopeLocksApi), instance, "instance is a EnvelopeLocksApi");
        }

        
        /// <summary>
        /// Test LockDeleteEnvelopeLock
        /// </summary>
        [Test]
        public void LockDeleteEnvelopeLockTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //var response = instance.LockDeleteEnvelopeLock(accountId, envelopeId);
            //Assert.IsInstanceOf<EnvelopeLocks> (response, "response is EnvelopeLocks");
        }
        
        /// <summary>
        /// Test LockGetEnvelopeLock
        /// </summary>
        [Test]
        public void LockGetEnvelopeLockTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //var response = instance.LockGetEnvelopeLock(accountId, envelopeId);
            //Assert.IsInstanceOf<EnvelopeLocks> (response, "response is EnvelopeLocks");
        }
        
        /// <summary>
        /// Test LockPostEnvelopeLock
        /// </summary>
        [Test]
        public void LockPostEnvelopeLockTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //LockRequest lockRequest = null;
            //var response = instance.LockPostEnvelopeLock(accountId, envelopeId, lockRequest);
            //Assert.IsInstanceOf<EnvelopeLocks> (response, "response is EnvelopeLocks");
        }
        
        /// <summary>
        /// Test LockPutEnvelopeLock
        /// </summary>
        [Test]
        public void LockPutEnvelopeLockTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //LockRequest lockRequest = null;
            //var response = instance.LockPutEnvelopeLock(accountId, envelopeId, lockRequest);
            //Assert.IsInstanceOf<EnvelopeLocks> (response, "response is EnvelopeLocks");
        }
        
    }

}
