/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using DocuSign.eSign.Api;
using NUnit.Framework;

namespace DocuSign.eSign.Test.Api
{
    /// <summary>
    ///  Class for testing EnvelopeDocumentVisibilityApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class EnvelopeDocumentVisibilityApiTests
    {
        private EnvelopeDocumentVisibilityApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new EnvelopeDocumentVisibilityApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EnvelopeDocumentVisibilityApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EnvelopeDocumentVisibilityApi
            //Assert.IsInstanceOfType(typeof(EnvelopeDocumentVisibilityApi), instance, "instance is a EnvelopeDocumentVisibilityApi");
        }

        
        /// <summary>
        /// Test RecipientsGetRecipientDocumentVisibility
        /// </summary>
        [Test]
        public void RecipientsGetRecipientDocumentVisibilityTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string recipientId = null;
            //var response = instance.RecipientsGetRecipientDocumentVisibility(accountId, envelopeId, recipientId);
            //Assert.IsInstanceOf<EnvelopeDocumentVisibility> (response, "response is EnvelopeDocumentVisibility");
        }
        
        /// <summary>
        /// Test RecipientsPutRecipientDocumentVisibility
        /// </summary>
        [Test]
        public void RecipientsPutRecipientDocumentVisibilityTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string recipientId = null;
            //EnvelopeDocumentVisibility envelopeDocumentVisibility = null;
            //var response = instance.RecipientsPutRecipientDocumentVisibility(accountId, envelopeId, recipientId, envelopeDocumentVisibility);
            //Assert.IsInstanceOf<EnvelopeDocumentVisibility> (response, "response is EnvelopeDocumentVisibility");
        }
        
        /// <summary>
        /// Test RecipientsPutRecipientsDocumentVisibility
        /// </summary>
        [Test]
        public void RecipientsPutRecipientsDocumentVisibilityTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //EnvelopeDocumentVisibility envelopeDocumentVisibility = null;
            //var response = instance.RecipientsPutRecipientsDocumentVisibility(accountId, envelopeId, envelopeDocumentVisibility);
            //Assert.IsInstanceOf<EnvelopeDocumentVisibility> (response, "response is EnvelopeDocumentVisibility");
        }
        
    }

}
