/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using DocuSign.eSign.Api;
using NUnit.Framework;

namespace DocuSign.eSign.Test.Api
{
    /// <summary>
    ///  Class for testing EnvelopeRecipientTabsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class EnvelopeRecipientTabsApiTests
    {
        private EnvelopeRecipientTabsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new EnvelopeRecipientTabsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EnvelopeRecipientTabsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EnvelopeRecipientTabsApi
            //Assert.IsInstanceOfType(typeof(EnvelopeRecipientTabsApi), instance, "instance is a EnvelopeRecipientTabsApi");
        }

        
        /// <summary>
        /// Test RecipientsDeleteRecipientTabs
        /// </summary>
        [Test]
        public void RecipientsDeleteRecipientTabsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string recipientId = null;
            //EnvelopeRecipientTabs envelopeRecipientTabs = null;
            //var response = instance.RecipientsDeleteRecipientTabs(accountId, envelopeId, recipientId, envelopeRecipientTabs);
            //Assert.IsInstanceOf<EnvelopeRecipientTabs> (response, "response is EnvelopeRecipientTabs");
        }
        
        /// <summary>
        /// Test RecipientsGetRecipientTabs
        /// </summary>
        [Test]
        public void RecipientsGetRecipientTabsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string recipientId = null;
            //string includeAnchorTabLocations = null;
            //string includeMetadata = null;
            //var response = instance.RecipientsGetRecipientTabs(accountId, envelopeId, recipientId, includeAnchorTabLocations, includeMetadata);
            //Assert.IsInstanceOf<EnvelopeRecipientTabs> (response, "response is EnvelopeRecipientTabs");
        }
        
        /// <summary>
        /// Test RecipientsPostRecipientTabs
        /// </summary>
        [Test]
        public void RecipientsPostRecipientTabsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string recipientId = null;
            //EnvelopeRecipientTabs envelopeRecipientTabs = null;
            //var response = instance.RecipientsPostRecipientTabs(accountId, envelopeId, recipientId, envelopeRecipientTabs);
            //Assert.IsInstanceOf<EnvelopeRecipientTabs> (response, "response is EnvelopeRecipientTabs");
        }
        
        /// <summary>
        /// Test RecipientsPutRecipientTabs
        /// </summary>
        [Test]
        public void RecipientsPutRecipientTabsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //string recipientId = null;
            //EnvelopeRecipientTabs envelopeRecipientTabs = null;
            //var response = instance.RecipientsPutRecipientTabs(accountId, envelopeId, recipientId, envelopeRecipientTabs);
            //Assert.IsInstanceOf<EnvelopeRecipientTabs> (response, "response is EnvelopeRecipientTabs");
        }
        
    }

}
