/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using DocuSign.eSign.Api;
using NUnit.Framework;

namespace DocuSign.eSign.Test.Api
{
    /// <summary>
    ///  Class for testing EnvelopeAttachmentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class EnvelopeAttachmentsApiTests
    {
        private EnvelopeAttachmentsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new EnvelopeAttachmentsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EnvelopeAttachmentsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' EnvelopeAttachmentsApi
            //Assert.IsInstanceOfType(typeof(EnvelopeAttachmentsApi), instance, "instance is a EnvelopeAttachmentsApi");
        }

        
        /// <summary>
        /// Test AttachmentsDeleteAttachments
        /// </summary>
        [Test]
        public void AttachmentsDeleteAttachmentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //EnvelopeAttachmentsRequest envelopeAttachmentsRequest = null;
            //var response = instance.AttachmentsDeleteAttachments(accountId, envelopeId, envelopeAttachmentsRequest);
            //Assert.IsInstanceOf<EnvelopeAttachmentsResult> (response, "response is EnvelopeAttachmentsResult");
        }
        
        /// <summary>
        /// Test AttachmentsGetAttachment
        /// </summary>
        [Test]
        public void AttachmentsGetAttachmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string attachmentId = null;
            //string envelopeId = null;
            //instance.AttachmentsGetAttachment(accountId, attachmentId, envelopeId);
            
        }
        
        /// <summary>
        /// Test AttachmentsGetAttachments
        /// </summary>
        [Test]
        public void AttachmentsGetAttachmentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //var response = instance.AttachmentsGetAttachments(accountId, envelopeId);
            //Assert.IsInstanceOf<EnvelopeAttachmentsResult> (response, "response is EnvelopeAttachmentsResult");
        }
        
        /// <summary>
        /// Test AttachmentsPutAttachment
        /// </summary>
        [Test]
        public void AttachmentsPutAttachmentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string attachmentId = null;
            //string envelopeId = null;
            //Attachment attachment = null;
            //var response = instance.AttachmentsPutAttachment(accountId, attachmentId, envelopeId, attachment);
            //Assert.IsInstanceOf<EnvelopeAttachmentsResult> (response, "response is EnvelopeAttachmentsResult");
        }
        
        /// <summary>
        /// Test AttachmentsPutAttachments
        /// </summary>
        [Test]
        public void AttachmentsPutAttachmentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string envelopeId = null;
            //EnvelopeAttachmentsRequest envelopeAttachmentsRequest = null;
            //var response = instance.AttachmentsPutAttachments(accountId, envelopeId, envelopeAttachmentsRequest);
            //Assert.IsInstanceOf<EnvelopeAttachmentsResult> (response, "response is EnvelopeAttachmentsResult");
        }
        
    }

}
