/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using DocuSign.eSign.Api;
using NUnit.Framework;

namespace DocuSign.eSign.Test.Api
{
    /// <summary>
    ///  Class for testing FoldersApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class FoldersApiTests
    {
        private FoldersApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new FoldersApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FoldersApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' FoldersApi
            //Assert.IsInstanceOfType(typeof(FoldersApi), instance, "instance is a FoldersApi");
        }

        
        /// <summary>
        /// Test FoldersGetFolderItems
        /// </summary>
        [Test]
        public void FoldersGetFolderItemsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string folderId = null;
            //string fromDate = null;
            //string includeItems = null;
            //string ownerEmail = null;
            //string ownerName = null;
            //string searchText = null;
            //string startPosition = null;
            //string status = null;
            //string toDate = null;
            //var response = instance.FoldersGetFolderItems(accountId, folderId, fromDate, includeItems, ownerEmail, ownerName, searchText, startPosition, status, toDate);
            //Assert.IsInstanceOf<FolderItemsResponse> (response, "response is FolderItemsResponse");
        }
        
        /// <summary>
        /// Test FoldersGetFolders
        /// </summary>
        [Test]
        public void FoldersGetFoldersTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string include = null;
            //string includeItems = null;
            //string startPosition = null;
            //string template = null;
            //string userFilter = null;
            //var response = instance.FoldersGetFolders(accountId, include, includeItems, startPosition, template, userFilter);
            //Assert.IsInstanceOf<Folders> (response, "response is Folders");
        }
        
        /// <summary>
        /// Test FoldersPutFolderById
        /// </summary>
        [Test]
        public void FoldersPutFolderByIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string folderId = null;
            //FoldersRequest foldersRequest = null;
            //var response = instance.FoldersPutFolderById(accountId, folderId, foldersRequest);
            //Assert.IsInstanceOf<Folders> (response, "response is Folders");
        }
        
        /// <summary>
        /// Test SearchFoldersGetSearchFolderContents
        /// </summary>
        [Test]
        public void SearchFoldersGetSearchFolderContentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string searchFolderId = null;
            //string all = null;
            //string count = null;
            //string fromDate = null;
            //string includeRecipients = null;
            //string order = null;
            //string orderBy = null;
            //string startPosition = null;
            //string toDate = null;
            //var response = instance.SearchFoldersGetSearchFolderContents(accountId, searchFolderId, all, count, fromDate, includeRecipients, order, orderBy, startPosition, toDate);
            //Assert.IsInstanceOf<FolderItemResponse> (response, "response is FolderItemResponse");
        }
        
    }

}
