/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using DocuSign.eSign.Api;
using NUnit.Framework;

namespace DocuSign.eSign.Test.Api
{
    /// <summary>
    ///  Class for testing InvoicesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class InvoicesApiTests
    {
        private InvoicesApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new InvoicesApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of InvoicesApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' InvoicesApi
            //Assert.IsInstanceOfType(typeof(InvoicesApi), instance, "instance is a InvoicesApi");
        }

        
        /// <summary>
        /// Test BillingInvoicesGetBillingInvoice
        /// </summary>
        [Test]
        public void BillingInvoicesGetBillingInvoiceTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string invoiceId = null;
            //var response = instance.BillingInvoicesGetBillingInvoice(accountId, invoiceId);
            //Assert.IsInstanceOf<Invoices> (response, "response is Invoices");
        }
        
        /// <summary>
        /// Test BillingInvoicesGetBillingInvoices
        /// </summary>
        [Test]
        public void BillingInvoicesGetBillingInvoicesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string fromDate = null;
            //string toDate = null;
            //var response = instance.BillingInvoicesGetBillingInvoices(accountId, fromDate, toDate);
            //Assert.IsInstanceOf<BillingInvoicesResponse> (response, "response is BillingInvoicesResponse");
        }
        
        /// <summary>
        /// Test BillingInvoicesGetBillingInvoicesPastDue
        /// </summary>
        [Test]
        public void BillingInvoicesGetBillingInvoicesPastDueTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //var response = instance.BillingInvoicesGetBillingInvoicesPastDue(accountId);
            //Assert.IsInstanceOf<BillingInvoicesSummary> (response, "response is BillingInvoicesSummary");
        }
        
    }

}
