/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using DocuSign.eSign.Api;
using NUnit.Framework;

namespace DocuSign.eSign.Test.Api
{
    /// <summary>
    ///  Class for testing PaymentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class PaymentsApiTests
    {
        private PaymentsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new PaymentsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PaymentsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' PaymentsApi
            //Assert.IsInstanceOfType(typeof(PaymentsApi), instance, "instance is a PaymentsApi");
        }

        
        /// <summary>
        /// Test BillingPaymentsGetPayment
        /// </summary>
        [Test]
        public void BillingPaymentsGetPaymentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string paymentId = null;
            //var response = instance.BillingPaymentsGetPayment(accountId, paymentId);
            //Assert.IsInstanceOf<Payments> (response, "response is Payments");
        }
        
        /// <summary>
        /// Test BillingPaymentsGetPaymentList
        /// </summary>
        [Test]
        public void BillingPaymentsGetPaymentListTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string fromDate = null;
            //string toDate = null;
            //var response = instance.BillingPaymentsGetPaymentList(accountId, fromDate, toDate);
            //Assert.IsInstanceOf<BillingPaymentsResponse> (response, "response is BillingPaymentsResponse");
        }
        
        /// <summary>
        /// Test BillingPaymentsPostPayment
        /// </summary>
        [Test]
        public void BillingPaymentsPostPaymentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //BillingPaymentRequest billingPaymentRequest = null;
            //var response = instance.BillingPaymentsPostPayment(accountId, billingPaymentRequest);
            //Assert.IsInstanceOf<BillingPaymentResponse> (response, "response is BillingPaymentResponse");
        }
        
    }

}
