/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using DocuSign.eSign.Api;
using NUnit.Framework;

namespace DocuSign.eSign.Test.Api
{
    /// <summary>
    ///  Class for testing SigningGroupsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class SigningGroupsApiTests
    {
        private SigningGroupsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new SigningGroupsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SigningGroupsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' SigningGroupsApi
            //Assert.IsInstanceOfType(typeof(SigningGroupsApi), instance, "instance is a SigningGroupsApi");
        }

        
        /// <summary>
        /// Test SigningGroupsDeleteSigningGroups
        /// </summary>
        [Test]
        public void SigningGroupsDeleteSigningGroupsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //SigningGroupInformation signingGroupInformation = null;
            //var response = instance.SigningGroupsDeleteSigningGroups(accountId, signingGroupInformation);
            //Assert.IsInstanceOf<SigningGroupInformation> (response, "response is SigningGroupInformation");
        }
        
        /// <summary>
        /// Test SigningGroupsGetSigningGroup
        /// </summary>
        [Test]
        public void SigningGroupsGetSigningGroupTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string signingGroupId = null;
            //var response = instance.SigningGroupsGetSigningGroup(accountId, signingGroupId);
            //Assert.IsInstanceOf<SigningGroups> (response, "response is SigningGroups");
        }
        
        /// <summary>
        /// Test SigningGroupsGetSigningGroups
        /// </summary>
        [Test]
        public void SigningGroupsGetSigningGroupsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string groupType = null;
            //string includeUsers = null;
            //var response = instance.SigningGroupsGetSigningGroups(accountId, groupType, includeUsers);
            //Assert.IsInstanceOf<SigningGroupInformation> (response, "response is SigningGroupInformation");
        }
        
        /// <summary>
        /// Test SigningGroupsPostSigningGroups
        /// </summary>
        [Test]
        public void SigningGroupsPostSigningGroupsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //SigningGroupInformation signingGroupInformation = null;
            //var response = instance.SigningGroupsPostSigningGroups(accountId, signingGroupInformation);
            //Assert.IsInstanceOf<SigningGroupInformation> (response, "response is SigningGroupInformation");
        }
        
        /// <summary>
        /// Test SigningGroupsPutSigningGroup
        /// </summary>
        [Test]
        public void SigningGroupsPutSigningGroupTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string signingGroupId = null;
            //SigningGroups signingGroups = null;
            //var response = instance.SigningGroupsPutSigningGroup(accountId, signingGroupId, signingGroups);
            //Assert.IsInstanceOf<SigningGroups> (response, "response is SigningGroups");
        }
        
        /// <summary>
        /// Test SigningGroupsPutSigningGroups
        /// </summary>
        [Test]
        public void SigningGroupsPutSigningGroupsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //SigningGroupInformation signingGroupInformation = null;
            //var response = instance.SigningGroupsPutSigningGroups(accountId, signingGroupInformation);
            //Assert.IsInstanceOf<SigningGroupInformation> (response, "response is SigningGroupInformation");
        }
        
    }

}
