/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using DocuSign.eSign.Api;
using NUnit.Framework;

namespace DocuSign.eSign.Test.Api
{
    /// <summary>
    ///  Class for testing TemplateCustomFieldsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class TemplateCustomFieldsApiTests
    {
        private TemplateCustomFieldsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new TemplateCustomFieldsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of TemplateCustomFieldsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' TemplateCustomFieldsApi
            //Assert.IsInstanceOfType(typeof(TemplateCustomFieldsApi), instance, "instance is a TemplateCustomFieldsApi");
        }

        
        /// <summary>
        /// Test CustomFieldsDeleteTemplateCustomFields
        /// </summary>
        [Test]
        public void CustomFieldsDeleteTemplateCustomFieldsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string templateId = null;
            //TemplateCustomFields templateCustomFields = null;
            //var response = instance.CustomFieldsDeleteTemplateCustomFields(accountId, templateId, templateCustomFields);
            //Assert.IsInstanceOf<TemplateCustomFields> (response, "response is TemplateCustomFields");
        }
        
        /// <summary>
        /// Test CustomFieldsGetTemplateCustomFields
        /// </summary>
        [Test]
        public void CustomFieldsGetTemplateCustomFieldsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string templateId = null;
            //var response = instance.CustomFieldsGetTemplateCustomFields(accountId, templateId);
            //Assert.IsInstanceOf<TemplateCustomFields> (response, "response is TemplateCustomFields");
        }
        
        /// <summary>
        /// Test CustomFieldsPostTemplateCustomFields
        /// </summary>
        [Test]
        public void CustomFieldsPostTemplateCustomFieldsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string templateId = null;
            //TemplateCustomFields templateCustomFields = null;
            //var response = instance.CustomFieldsPostTemplateCustomFields(accountId, templateId, templateCustomFields);
            //Assert.IsInstanceOf<TemplateCustomFields> (response, "response is TemplateCustomFields");
        }
        
        /// <summary>
        /// Test CustomFieldsPutTemplateCustomFields
        /// </summary>
        [Test]
        public void CustomFieldsPutTemplateCustomFieldsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string templateId = null;
            //TemplateCustomFields templateCustomFields = null;
            //var response = instance.CustomFieldsPutTemplateCustomFields(accountId, templateId, templateCustomFields);
            //Assert.IsInstanceOf<TemplateCustomFields> (response, "response is TemplateCustomFields");
        }
        
    }

}
