/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using DocuSign.eSign.Api;
using NUnit.Framework;

namespace DocuSign.eSign.Test.Api
{
    /// <summary>
    ///  Class for testing UserCustomSettingsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class UserCustomSettingsApiTests
    {
        private UserCustomSettingsApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new UserCustomSettingsApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserCustomSettingsApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' UserCustomSettingsApi
            //Assert.IsInstanceOfType(typeof(UserCustomSettingsApi), instance, "instance is a UserCustomSettingsApi");
        }

        
        /// <summary>
        /// Test UserCustomSettingsDeleteCustomSettings
        /// </summary>
        [Test]
        public void UserCustomSettingsDeleteCustomSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string userId = null;
            //UserCustomSettings userCustomSettings = null;
            //var response = instance.UserCustomSettingsDeleteCustomSettings(accountId, userId, userCustomSettings);
            //Assert.IsInstanceOf<UserCustomSettings> (response, "response is UserCustomSettings");
        }
        
        /// <summary>
        /// Test UserCustomSettingsGetCustomSettings
        /// </summary>
        [Test]
        public void UserCustomSettingsGetCustomSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string userId = null;
            //var response = instance.UserCustomSettingsGetCustomSettings(accountId, userId);
            //Assert.IsInstanceOf<UserCustomSettings> (response, "response is UserCustomSettings");
        }
        
        /// <summary>
        /// Test UserCustomSettingsPutCustomSettings
        /// </summary>
        [Test]
        public void UserCustomSettingsPutCustomSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string accountId = null;
            //string userId = null;
            //UserCustomSettings userCustomSettings = null;
            //var response = instance.UserCustomSettingsPutCustomSettings(accountId, userId, userCustomSettings);
            //Assert.IsInstanceOf<UserCustomSettings> (response, "response is UserCustomSettings");
        }
        
    }

}
