/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing AccountTabSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccountTabSettingsTests
    {
        // TODO uncomment below to declare an instance variable for AccountTabSettings
        //private AccountTabSettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccountTabSettings
            //instance = new AccountTabSettings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountTabSettings
        /// </summary>
        [Test]
        public void AccountTabSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccountTabSettings
            //Assert.IsInstanceOfType<AccountTabSettings> (instance, "variable 'instance' is a AccountTabSettings");
        }

        /// <summary>
        /// Test the property 'AllowTabOrder'
        /// </summary>
        [Test]
        public void AllowTabOrderTest()
        {
            // TODO unit test for the property 'AllowTabOrder'
        }
        /// <summary>
        /// Test the property 'AllowTabOrderMetadata'
        /// </summary>
        [Test]
        public void AllowTabOrderMetadataTest()
        {
            // TODO unit test for the property 'AllowTabOrderMetadata'
        }
        /// <summary>
        /// Test the property 'ApproveDeclineTabsEnabled'
        /// </summary>
        [Test]
        public void ApproveDeclineTabsEnabledTest()
        {
            // TODO unit test for the property 'ApproveDeclineTabsEnabled'
        }
        /// <summary>
        /// Test the property 'ApproveDeclineTabsMetadata'
        /// </summary>
        [Test]
        public void ApproveDeclineTabsMetadataTest()
        {
            // TODO unit test for the property 'ApproveDeclineTabsMetadata'
        }
        /// <summary>
        /// Test the property 'CalculatedFieldsEnabled'
        /// </summary>
        [Test]
        public void CalculatedFieldsEnabledTest()
        {
            // TODO unit test for the property 'CalculatedFieldsEnabled'
        }
        /// <summary>
        /// Test the property 'CalculatedFieldsMetadata'
        /// </summary>
        [Test]
        public void CalculatedFieldsMetadataTest()
        {
            // TODO unit test for the property 'CalculatedFieldsMetadata'
        }
        /// <summary>
        /// Test the property 'CheckboxTabsEnabled'
        /// </summary>
        [Test]
        public void CheckboxTabsEnabledTest()
        {
            // TODO unit test for the property 'CheckboxTabsEnabled'
        }
        /// <summary>
        /// Test the property 'CheckboxTabsMetadata'
        /// </summary>
        [Test]
        public void CheckboxTabsMetadataTest()
        {
            // TODO unit test for the property 'CheckboxTabsMetadata'
        }
        /// <summary>
        /// Test the property 'DataFieldRegexEnabled'
        /// </summary>
        [Test]
        public void DataFieldRegexEnabledTest()
        {
            // TODO unit test for the property 'DataFieldRegexEnabled'
        }
        /// <summary>
        /// Test the property 'DataFieldRegexMetadata'
        /// </summary>
        [Test]
        public void DataFieldRegexMetadataTest()
        {
            // TODO unit test for the property 'DataFieldRegexMetadata'
        }
        /// <summary>
        /// Test the property 'DataFieldSizeEnabled'
        /// </summary>
        [Test]
        public void DataFieldSizeEnabledTest()
        {
            // TODO unit test for the property 'DataFieldSizeEnabled'
        }
        /// <summary>
        /// Test the property 'DataFieldSizeMetadata'
        /// </summary>
        [Test]
        public void DataFieldSizeMetadataTest()
        {
            // TODO unit test for the property 'DataFieldSizeMetadata'
        }
        /// <summary>
        /// Test the property 'FirstLastEmailTabsEnabled'
        /// </summary>
        [Test]
        public void FirstLastEmailTabsEnabledTest()
        {
            // TODO unit test for the property 'FirstLastEmailTabsEnabled'
        }
        /// <summary>
        /// Test the property 'FirstLastEmailTabsMetadata'
        /// </summary>
        [Test]
        public void FirstLastEmailTabsMetadataTest()
        {
            // TODO unit test for the property 'FirstLastEmailTabsMetadata'
        }
        /// <summary>
        /// Test the property 'ListTabsEnabled'
        /// </summary>
        [Test]
        public void ListTabsEnabledTest()
        {
            // TODO unit test for the property 'ListTabsEnabled'
        }
        /// <summary>
        /// Test the property 'ListTabsMetadata'
        /// </summary>
        [Test]
        public void ListTabsMetadataTest()
        {
            // TODO unit test for the property 'ListTabsMetadata'
        }
        /// <summary>
        /// Test the property 'NoteTabsEnabled'
        /// </summary>
        [Test]
        public void NoteTabsEnabledTest()
        {
            // TODO unit test for the property 'NoteTabsEnabled'
        }
        /// <summary>
        /// Test the property 'NoteTabsMetadata'
        /// </summary>
        [Test]
        public void NoteTabsMetadataTest()
        {
            // TODO unit test for the property 'NoteTabsMetadata'
        }
        /// <summary>
        /// Test the property 'RadioTabsEnabled'
        /// </summary>
        [Test]
        public void RadioTabsEnabledTest()
        {
            // TODO unit test for the property 'RadioTabsEnabled'
        }
        /// <summary>
        /// Test the property 'RadioTabsMetadata'
        /// </summary>
        [Test]
        public void RadioTabsMetadataTest()
        {
            // TODO unit test for the property 'RadioTabsMetadata'
        }
        /// <summary>
        /// Test the property 'SavingCustomTabsEnabled'
        /// </summary>
        [Test]
        public void SavingCustomTabsEnabledTest()
        {
            // TODO unit test for the property 'SavingCustomTabsEnabled'
        }
        /// <summary>
        /// Test the property 'SavingCustomTabsMetadata'
        /// </summary>
        [Test]
        public void SavingCustomTabsMetadataTest()
        {
            // TODO unit test for the property 'SavingCustomTabsMetadata'
        }
        /// <summary>
        /// Test the property 'SenderToChangeTabAssignmentsEnabled'
        /// </summary>
        [Test]
        public void SenderToChangeTabAssignmentsEnabledTest()
        {
            // TODO unit test for the property 'SenderToChangeTabAssignmentsEnabled'
        }
        /// <summary>
        /// Test the property 'SenderToChangeTabAssignmentsMetadata'
        /// </summary>
        [Test]
        public void SenderToChangeTabAssignmentsMetadataTest()
        {
            // TODO unit test for the property 'SenderToChangeTabAssignmentsMetadata'
        }
        /// <summary>
        /// Test the property 'SharedCustomTabsEnabled'
        /// </summary>
        [Test]
        public void SharedCustomTabsEnabledTest()
        {
            // TODO unit test for the property 'SharedCustomTabsEnabled'
        }
        /// <summary>
        /// Test the property 'SharedCustomTabsMetadata'
        /// </summary>
        [Test]
        public void SharedCustomTabsMetadataTest()
        {
            // TODO unit test for the property 'SharedCustomTabsMetadata'
        }
        /// <summary>
        /// Test the property 'TabDataLabelEnabled'
        /// </summary>
        [Test]
        public void TabDataLabelEnabledTest()
        {
            // TODO unit test for the property 'TabDataLabelEnabled'
        }
        /// <summary>
        /// Test the property 'TabDataLabelMetadata'
        /// </summary>
        [Test]
        public void TabDataLabelMetadataTest()
        {
            // TODO unit test for the property 'TabDataLabelMetadata'
        }
        /// <summary>
        /// Test the property 'TabLocationEnabled'
        /// </summary>
        [Test]
        public void TabLocationEnabledTest()
        {
            // TODO unit test for the property 'TabLocationEnabled'
        }
        /// <summary>
        /// Test the property 'TabLocationMetadata'
        /// </summary>
        [Test]
        public void TabLocationMetadataTest()
        {
            // TODO unit test for the property 'TabLocationMetadata'
        }
        /// <summary>
        /// Test the property 'TabLockingEnabled'
        /// </summary>
        [Test]
        public void TabLockingEnabledTest()
        {
            // TODO unit test for the property 'TabLockingEnabled'
        }
        /// <summary>
        /// Test the property 'TabLockingMetadata'
        /// </summary>
        [Test]
        public void TabLockingMetadataTest()
        {
            // TODO unit test for the property 'TabLockingMetadata'
        }
        /// <summary>
        /// Test the property 'TabScaleEnabled'
        /// </summary>
        [Test]
        public void TabScaleEnabledTest()
        {
            // TODO unit test for the property 'TabScaleEnabled'
        }
        /// <summary>
        /// Test the property 'TabScaleMetadata'
        /// </summary>
        [Test]
        public void TabScaleMetadataTest()
        {
            // TODO unit test for the property 'TabScaleMetadata'
        }
        /// <summary>
        /// Test the property 'TabTextFormattingEnabled'
        /// </summary>
        [Test]
        public void TabTextFormattingEnabledTest()
        {
            // TODO unit test for the property 'TabTextFormattingEnabled'
        }
        /// <summary>
        /// Test the property 'TabTextFormattingMetadata'
        /// </summary>
        [Test]
        public void TabTextFormattingMetadataTest()
        {
            // TODO unit test for the property 'TabTextFormattingMetadata'
        }
        /// <summary>
        /// Test the property 'TextTabsEnabled'
        /// </summary>
        [Test]
        public void TextTabsEnabledTest()
        {
            // TODO unit test for the property 'TextTabsEnabled'
        }
        /// <summary>
        /// Test the property 'TextTabsMetadata'
        /// </summary>
        [Test]
        public void TextTabsMetadataTest()
        {
            // TODO unit test for the property 'TextTabsMetadata'
        }

    }

}
