/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing AccountWatermarks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccountWatermarksTests
    {
        // TODO uncomment below to declare an instance variable for AccountWatermarks
        //private AccountWatermarks instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccountWatermarks
            //instance = new AccountWatermarks();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountWatermarks
        /// </summary>
        [Test]
        public void AccountWatermarksInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccountWatermarks
            //Assert.IsInstanceOfType<AccountWatermarks> (instance, "variable 'instance' is a AccountWatermarks");
        }

        /// <summary>
        /// Test the property 'DisplayAngle'
        /// </summary>
        [Test]
        public void DisplayAngleTest()
        {
            // TODO unit test for the property 'DisplayAngle'
        }
        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Test]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }
        /// <summary>
        /// Test the property 'Font'
        /// </summary>
        [Test]
        public void FontTest()
        {
            // TODO unit test for the property 'Font'
        }
        /// <summary>
        /// Test the property 'FontColor'
        /// </summary>
        [Test]
        public void FontColorTest()
        {
            // TODO unit test for the property 'FontColor'
        }
        /// <summary>
        /// Test the property 'FontSize'
        /// </summary>
        [Test]
        public void FontSizeTest()
        {
            // TODO unit test for the property 'FontSize'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ImageBase64'
        /// </summary>
        [Test]
        public void ImageBase64Test()
        {
            // TODO unit test for the property 'ImageBase64'
        }
        /// <summary>
        /// Test the property 'Transparency'
        /// </summary>
        [Test]
        public void TransparencyTest()
        {
            // TODO unit test for the property 'Transparency'
        }
        /// <summary>
        /// Test the property 'WatermarkText'
        /// </summary>
        [Test]
        public void WatermarkTextTest()
        {
            // TODO unit test for the property 'WatermarkText'
        }

    }

}
