/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing AccountSignatureProvider
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AccountSignatureProviderTests
    {
        // TODO uncomment below to declare an instance variable for AccountSignatureProvider
        //private AccountSignatureProvider instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AccountSignatureProvider
            //instance = new AccountSignatureProvider();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountSignatureProvider
        /// </summary>
        [Test]
        public void AccountSignatureProviderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccountSignatureProvider
            //Assert.IsInstanceOfType<AccountSignatureProvider> (instance, "variable 'instance' is a AccountSignatureProvider");
        }

        /// <summary>
        /// Test the property 'IsRequired'
        /// </summary>
        [Test]
        public void IsRequiredTest()
        {
            // TODO unit test for the property 'IsRequired'
        }
        /// <summary>
        /// Test the property 'Priority'
        /// </summary>
        [Test]
        public void PriorityTest()
        {
            // TODO unit test for the property 'Priority'
        }
        /// <summary>
        /// Test the property 'SignatureProviderDisplayName'
        /// </summary>
        [Test]
        public void SignatureProviderDisplayNameTest()
        {
            // TODO unit test for the property 'SignatureProviderDisplayName'
        }
        /// <summary>
        /// Test the property 'SignatureProviderId'
        /// </summary>
        [Test]
        public void SignatureProviderIdTest()
        {
            // TODO unit test for the property 'SignatureProviderId'
        }
        /// <summary>
        /// Test the property 'SignatureProviderName'
        /// </summary>
        [Test]
        public void SignatureProviderNameTest()
        {
            // TODO unit test for the property 'SignatureProviderName'
        }
        /// <summary>
        /// Test the property 'SignatureProviderOptionsMetadata'
        /// </summary>
        [Test]
        public void SignatureProviderOptionsMetadataTest()
        {
            // TODO unit test for the property 'SignatureProviderOptionsMetadata'
        }
        /// <summary>
        /// Test the property 'SignatureProviderRequiredOptions'
        /// </summary>
        [Test]
        public void SignatureProviderRequiredOptionsTest()
        {
            // TODO unit test for the property 'SignatureProviderRequiredOptions'
        }

    }

}
