/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing AuthenticationMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AuthenticationMethodTests
    {
        // TODO uncomment below to declare an instance variable for AuthenticationMethod
        //private AuthenticationMethod instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AuthenticationMethod
            //instance = new AuthenticationMethod();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AuthenticationMethod
        /// </summary>
        [Test]
        public void AuthenticationMethodInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AuthenticationMethod
            //Assert.IsInstanceOfType<AuthenticationMethod> (instance, "variable 'instance' is a AuthenticationMethod");
        }

        /// <summary>
        /// Test the property 'AuthenticationType'
        /// </summary>
        [Test]
        public void AuthenticationTypeTest()
        {
            // TODO unit test for the property 'AuthenticationType'
        }
        /// <summary>
        /// Test the property 'LastProvider'
        /// </summary>
        [Test]
        public void LastProviderTest()
        {
            // TODO unit test for the property 'LastProvider'
        }
        /// <summary>
        /// Test the property 'LastTimestamp'
        /// </summary>
        [Test]
        public void LastTimestampTest()
        {
            // TODO unit test for the property 'LastTimestamp'
        }
        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Test]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }

    }

}
