/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing BillingPlanInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BillingPlanInformationTests
    {
        // TODO uncomment below to declare an instance variable for BillingPlanInformation
        //private BillingPlanInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BillingPlanInformation
            //instance = new BillingPlanInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BillingPlanInformation
        /// </summary>
        [Test]
        public void BillingPlanInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BillingPlanInformation
            //Assert.IsInstanceOfType<BillingPlanInformation> (instance, "variable 'instance' is a BillingPlanInformation");
        }

        /// <summary>
        /// Test the property 'AppStoreReceipt'
        /// </summary>
        [Test]
        public void AppStoreReceiptTest()
        {
            // TODO unit test for the property 'AppStoreReceipt'
        }
        /// <summary>
        /// Test the property 'BillingAddress'
        /// </summary>
        [Test]
        public void BillingAddressTest()
        {
            // TODO unit test for the property 'BillingAddress'
        }
        /// <summary>
        /// Test the property 'CreditCardInformation'
        /// </summary>
        [Test]
        public void CreditCardInformationTest()
        {
            // TODO unit test for the property 'CreditCardInformation'
        }
        /// <summary>
        /// Test the property 'DowngradeReason'
        /// </summary>
        [Test]
        public void DowngradeReasonTest()
        {
            // TODO unit test for the property 'DowngradeReason'
        }
        /// <summary>
        /// Test the property 'EnableSupport'
        /// </summary>
        [Test]
        public void EnableSupportTest()
        {
            // TODO unit test for the property 'EnableSupport'
        }
        /// <summary>
        /// Test the property 'IncludedSeats'
        /// </summary>
        [Test]
        public void IncludedSeatsTest()
        {
            // TODO unit test for the property 'IncludedSeats'
        }
        /// <summary>
        /// Test the property 'IncrementalSeats'
        /// </summary>
        [Test]
        public void IncrementalSeatsTest()
        {
            // TODO unit test for the property 'IncrementalSeats'
        }
        /// <summary>
        /// Test the property 'PaymentProcessorInformation'
        /// </summary>
        [Test]
        public void PaymentProcessorInformationTest()
        {
            // TODO unit test for the property 'PaymentProcessorInformation'
        }
        /// <summary>
        /// Test the property 'PlanInformation'
        /// </summary>
        [Test]
        public void PlanInformationTest()
        {
            // TODO unit test for the property 'PlanInformation'
        }
        /// <summary>
        /// Test the property 'ReferralInformation'
        /// </summary>
        [Test]
        public void ReferralInformationTest()
        {
            // TODO unit test for the property 'ReferralInformation'
        }
        /// <summary>
        /// Test the property 'RenewalStatus'
        /// </summary>
        [Test]
        public void RenewalStatusTest()
        {
            // TODO unit test for the property 'RenewalStatus'
        }
        /// <summary>
        /// Test the property 'SaleDiscountAmount'
        /// </summary>
        [Test]
        public void SaleDiscountAmountTest()
        {
            // TODO unit test for the property 'SaleDiscountAmount'
        }
        /// <summary>
        /// Test the property 'SaleDiscountFixedAmount'
        /// </summary>
        [Test]
        public void SaleDiscountFixedAmountTest()
        {
            // TODO unit test for the property 'SaleDiscountFixedAmount'
        }
        /// <summary>
        /// Test the property 'SaleDiscountPercent'
        /// </summary>
        [Test]
        public void SaleDiscountPercentTest()
        {
            // TODO unit test for the property 'SaleDiscountPercent'
        }
        /// <summary>
        /// Test the property 'SaleDiscountPeriods'
        /// </summary>
        [Test]
        public void SaleDiscountPeriodsTest()
        {
            // TODO unit test for the property 'SaleDiscountPeriods'
        }
        /// <summary>
        /// Test the property 'SaleDiscountSeatPriceOverride'
        /// </summary>
        [Test]
        public void SaleDiscountSeatPriceOverrideTest()
        {
            // TODO unit test for the property 'SaleDiscountSeatPriceOverride'
        }

    }

}
