/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing BillingCharge
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BillingChargeTests
    {
        // TODO uncomment below to declare an instance variable for BillingCharge
        //private BillingCharge instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BillingCharge
            //instance = new BillingCharge();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BillingCharge
        /// </summary>
        [Test]
        public void BillingChargeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BillingCharge
            //Assert.IsInstanceOfType<BillingCharge> (instance, "variable 'instance' is a BillingCharge");
        }

        /// <summary>
        /// Test the property 'AllowedQuantity'
        /// </summary>
        [Test]
        public void AllowedQuantityTest()
        {
            // TODO unit test for the property 'AllowedQuantity'
        }
        /// <summary>
        /// Test the property 'Blocked'
        /// </summary>
        [Test]
        public void BlockedTest()
        {
            // TODO unit test for the property 'Blocked'
        }
        /// <summary>
        /// Test the property 'ChargeName'
        /// </summary>
        [Test]
        public void ChargeNameTest()
        {
            // TODO unit test for the property 'ChargeName'
        }
        /// <summary>
        /// Test the property 'ChargeType'
        /// </summary>
        [Test]
        public void ChargeTypeTest()
        {
            // TODO unit test for the property 'ChargeType'
        }
        /// <summary>
        /// Test the property 'ChargeUnitOfMeasure'
        /// </summary>
        [Test]
        public void ChargeUnitOfMeasureTest()
        {
            // TODO unit test for the property 'ChargeUnitOfMeasure'
        }
        /// <summary>
        /// Test the property 'Discounts'
        /// </summary>
        [Test]
        public void DiscountsTest()
        {
            // TODO unit test for the property 'Discounts'
        }
        /// <summary>
        /// Test the property 'FirstEffectiveDate'
        /// </summary>
        [Test]
        public void FirstEffectiveDateTest()
        {
            // TODO unit test for the property 'FirstEffectiveDate'
        }
        /// <summary>
        /// Test the property 'IncludedQuantity'
        /// </summary>
        [Test]
        public void IncludedQuantityTest()
        {
            // TODO unit test for the property 'IncludedQuantity'
        }
        /// <summary>
        /// Test the property 'IncrementalQuantity'
        /// </summary>
        [Test]
        public void IncrementalQuantityTest()
        {
            // TODO unit test for the property 'IncrementalQuantity'
        }
        /// <summary>
        /// Test the property 'LastEffectiveDate'
        /// </summary>
        [Test]
        public void LastEffectiveDateTest()
        {
            // TODO unit test for the property 'LastEffectiveDate'
        }
        /// <summary>
        /// Test the property 'Prices'
        /// </summary>
        [Test]
        public void PricesTest()
        {
            // TODO unit test for the property 'Prices'
        }
        /// <summary>
        /// Test the property 'UnitPrice'
        /// </summary>
        [Test]
        public void UnitPriceTest()
        {
            // TODO unit test for the property 'UnitPrice'
        }
        /// <summary>
        /// Test the property 'UsedQuantity'
        /// </summary>
        [Test]
        public void UsedQuantityTest()
        {
            // TODO unit test for the property 'UsedQuantity'
        }

    }

}
