/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing BillingPlanUpdateResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BillingPlanUpdateResponseTests
    {
        // TODO uncomment below to declare an instance variable for BillingPlanUpdateResponse
        //private BillingPlanUpdateResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BillingPlanUpdateResponse
            //instance = new BillingPlanUpdateResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BillingPlanUpdateResponse
        /// </summary>
        [Test]
        public void BillingPlanUpdateResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BillingPlanUpdateResponse
            //Assert.IsInstanceOfType<BillingPlanUpdateResponse> (instance, "variable 'instance' is a BillingPlanUpdateResponse");
        }

        /// <summary>
        /// Test the property 'AccountPaymentMethod'
        /// </summary>
        [Test]
        public void AccountPaymentMethodTest()
        {
            // TODO unit test for the property 'AccountPaymentMethod'
        }
        /// <summary>
        /// Test the property 'BillingPlanPreview'
        /// </summary>
        [Test]
        public void BillingPlanPreviewTest()
        {
            // TODO unit test for the property 'BillingPlanPreview'
        }
        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Test]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }
        /// <summary>
        /// Test the property 'IncludedSeats'
        /// </summary>
        [Test]
        public void IncludedSeatsTest()
        {
            // TODO unit test for the property 'IncludedSeats'
        }
        /// <summary>
        /// Test the property 'PaymentCycle'
        /// </summary>
        [Test]
        public void PaymentCycleTest()
        {
            // TODO unit test for the property 'PaymentCycle'
        }
        /// <summary>
        /// Test the property 'PaymentMethod'
        /// </summary>
        [Test]
        public void PaymentMethodTest()
        {
            // TODO unit test for the property 'PaymentMethod'
        }
        /// <summary>
        /// Test the property 'PlanId'
        /// </summary>
        [Test]
        public void PlanIdTest()
        {
            // TODO unit test for the property 'PlanId'
        }
        /// <summary>
        /// Test the property 'PlanName'
        /// </summary>
        [Test]
        public void PlanNameTest()
        {
            // TODO unit test for the property 'PlanName'
        }

    }

}
