/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing BillingPlans
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BillingPlansTests
    {
        // TODO uncomment below to declare an instance variable for BillingPlans
        //private BillingPlans instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BillingPlans
            //instance = new BillingPlans();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BillingPlans
        /// </summary>
        [Test]
        public void BillingPlansInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BillingPlans
            //Assert.IsInstanceOfType<BillingPlans> (instance, "variable 'instance' is a BillingPlans");
        }

        /// <summary>
        /// Test the property 'BillingAddress'
        /// </summary>
        [Test]
        public void BillingAddressTest()
        {
            // TODO unit test for the property 'BillingAddress'
        }
        /// <summary>
        /// Test the property 'BillingAddressIsCreditCardAddress'
        /// </summary>
        [Test]
        public void BillingAddressIsCreditCardAddressTest()
        {
            // TODO unit test for the property 'BillingAddressIsCreditCardAddress'
        }
        /// <summary>
        /// Test the property 'BillingPlan'
        /// </summary>
        [Test]
        public void BillingPlanTest()
        {
            // TODO unit test for the property 'BillingPlan'
        }
        /// <summary>
        /// Test the property 'CreditCardInformation'
        /// </summary>
        [Test]
        public void CreditCardInformationTest()
        {
            // TODO unit test for the property 'CreditCardInformation'
        }
        /// <summary>
        /// Test the property 'PaymentProcessorInformation'
        /// </summary>
        [Test]
        public void PaymentProcessorInformationTest()
        {
            // TODO unit test for the property 'PaymentProcessorInformation'
        }
        /// <summary>
        /// Test the property 'ReferralInformation'
        /// </summary>
        [Test]
        public void ReferralInformationTest()
        {
            // TODO unit test for the property 'ReferralInformation'
        }
        /// <summary>
        /// Test the property 'SuccessorPlans'
        /// </summary>
        [Test]
        public void SuccessorPlansTest()
        {
            // TODO unit test for the property 'SuccessorPlans'
        }

    }

}
