/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing BrandResourceUrls
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BrandResourceUrlsTests
    {
        // TODO uncomment below to declare an instance variable for BrandResourceUrls
        //private BrandResourceUrls instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BrandResourceUrls
            //instance = new BrandResourceUrls();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BrandResourceUrls
        /// </summary>
        [Test]
        public void BrandResourceUrlsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BrandResourceUrls
            //Assert.IsInstanceOfType<BrandResourceUrls> (instance, "variable 'instance' is a BrandResourceUrls");
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Sending'
        /// </summary>
        [Test]
        public void SendingTest()
        {
            // TODO unit test for the property 'Sending'
        }
        /// <summary>
        /// Test the property 'Signing'
        /// </summary>
        [Test]
        public void SigningTest()
        {
            // TODO unit test for the property 'Signing'
        }
        /// <summary>
        /// Test the property 'SigningCaptive'
        /// </summary>
        [Test]
        public void SigningCaptiveTest()
        {
            // TODO unit test for the property 'SigningCaptive'
        }

    }

}
