/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing BulkEnvelopeStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BulkEnvelopeStatusTests
    {
        // TODO uncomment below to declare an instance variable for BulkEnvelopeStatus
        //private BulkEnvelopeStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BulkEnvelopeStatus
            //instance = new BulkEnvelopeStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BulkEnvelopeStatus
        /// </summary>
        [Test]
        public void BulkEnvelopeStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BulkEnvelopeStatus
            //Assert.IsInstanceOfType<BulkEnvelopeStatus> (instance, "variable 'instance' is a BulkEnvelopeStatus");
        }

        /// <summary>
        /// Test the property 'BatchId'
        /// </summary>
        [Test]
        public void BatchIdTest()
        {
            // TODO unit test for the property 'BatchId'
        }
        /// <summary>
        /// Test the property 'BatchSize'
        /// </summary>
        [Test]
        public void BatchSizeTest()
        {
            // TODO unit test for the property 'BatchSize'
        }
        /// <summary>
        /// Test the property 'BulkEnvelopes'
        /// </summary>
        [Test]
        public void BulkEnvelopesTest()
        {
            // TODO unit test for the property 'BulkEnvelopes'
        }
        /// <summary>
        /// Test the property 'BulkEnvelopesBatchUri'
        /// </summary>
        [Test]
        public void BulkEnvelopesBatchUriTest()
        {
            // TODO unit test for the property 'BulkEnvelopesBatchUri'
        }
        /// <summary>
        /// Test the property 'EndPosition'
        /// </summary>
        [Test]
        public void EndPositionTest()
        {
            // TODO unit test for the property 'EndPosition'
        }
        /// <summary>
        /// Test the property 'Failed'
        /// </summary>
        [Test]
        public void FailedTest()
        {
            // TODO unit test for the property 'Failed'
        }
        /// <summary>
        /// Test the property 'NextUri'
        /// </summary>
        [Test]
        public void NextUriTest()
        {
            // TODO unit test for the property 'NextUri'
        }
        /// <summary>
        /// Test the property 'PreviousUri'
        /// </summary>
        [Test]
        public void PreviousUriTest()
        {
            // TODO unit test for the property 'PreviousUri'
        }
        /// <summary>
        /// Test the property 'Queued'
        /// </summary>
        [Test]
        public void QueuedTest()
        {
            // TODO unit test for the property 'Queued'
        }
        /// <summary>
        /// Test the property 'ResultSetSize'
        /// </summary>
        [Test]
        public void ResultSetSizeTest()
        {
            // TODO unit test for the property 'ResultSetSize'
        }
        /// <summary>
        /// Test the property 'Sent'
        /// </summary>
        [Test]
        public void SentTest()
        {
            // TODO unit test for the property 'Sent'
        }
        /// <summary>
        /// Test the property 'StartPosition'
        /// </summary>
        [Test]
        public void StartPositionTest()
        {
            // TODO unit test for the property 'StartPosition'
        }
        /// <summary>
        /// Test the property 'SubmittedDate'
        /// </summary>
        [Test]
        public void SubmittedDateTest()
        {
            // TODO unit test for the property 'SubmittedDate'
        }
        /// <summary>
        /// Test the property 'TotalSetSize'
        /// </summary>
        [Test]
        public void TotalSetSizeTest()
        {
            // TODO unit test for the property 'TotalSetSize'
        }

    }

}
