/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing BulkRecipient
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BulkRecipientTests
    {
        // TODO uncomment below to declare an instance variable for BulkRecipient
        //private BulkRecipient instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BulkRecipient
            //instance = new BulkRecipient();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BulkRecipient
        /// </summary>
        [Test]
        public void BulkRecipientInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BulkRecipient
            //Assert.IsInstanceOfType<BulkRecipient> (instance, "variable 'instance' is a BulkRecipient");
        }

        /// <summary>
        /// Test the property 'AccessCode'
        /// </summary>
        [Test]
        public void AccessCodeTest()
        {
            // TODO unit test for the property 'AccessCode'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [Test]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'Identification'
        /// </summary>
        [Test]
        public void IdentificationTest()
        {
            // TODO unit test for the property 'Identification'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Note'
        /// </summary>
        [Test]
        public void NoteTest()
        {
            // TODO unit test for the property 'Note'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'RecipientSignatureProviderInfo'
        /// </summary>
        [Test]
        public void RecipientSignatureProviderInfoTest()
        {
            // TODO unit test for the property 'RecipientSignatureProviderInfo'
        }
        /// <summary>
        /// Test the property 'RowNumber'
        /// </summary>
        [Test]
        public void RowNumberTest()
        {
            // TODO unit test for the property 'RowNumber'
        }
        /// <summary>
        /// Test the property 'TabLabels'
        /// </summary>
        [Test]
        public void TabLabelsTest()
        {
            // TODO unit test for the property 'TabLabels'
        }

    }

}
