/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing ChunkedUploads
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChunkedUploadsTests
    {
        // TODO uncomment below to declare an instance variable for ChunkedUploads
        //private ChunkedUploads instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChunkedUploads
            //instance = new ChunkedUploads();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChunkedUploads
        /// </summary>
        [Test]
        public void ChunkedUploadsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChunkedUploads
            //Assert.IsInstanceOfType<ChunkedUploads> (instance, "variable 'instance' is a ChunkedUploads");
        }

        /// <summary>
        /// Test the property 'Checksum'
        /// </summary>
        [Test]
        public void ChecksumTest()
        {
            // TODO unit test for the property 'Checksum'
        }
        /// <summary>
        /// Test the property 'ChunkedUploadId'
        /// </summary>
        [Test]
        public void ChunkedUploadIdTest()
        {
            // TODO unit test for the property 'ChunkedUploadId'
        }
        /// <summary>
        /// Test the property 'ChunkedUploadParts'
        /// </summary>
        [Test]
        public void ChunkedUploadPartsTest()
        {
            // TODO unit test for the property 'ChunkedUploadParts'
        }
        /// <summary>
        /// Test the property 'ChunkedUploadUri'
        /// </summary>
        [Test]
        public void ChunkedUploadUriTest()
        {
            // TODO unit test for the property 'ChunkedUploadUri'
        }
        /// <summary>
        /// Test the property 'Committed'
        /// </summary>
        [Test]
        public void CommittedTest()
        {
            // TODO unit test for the property 'Committed'
        }
        /// <summary>
        /// Test the property 'ExpirationDateTime'
        /// </summary>
        [Test]
        public void ExpirationDateTimeTest()
        {
            // TODO unit test for the property 'ExpirationDateTime'
        }
        /// <summary>
        /// Test the property 'MaxChunkedUploadParts'
        /// </summary>
        [Test]
        public void MaxChunkedUploadPartsTest()
        {
            // TODO unit test for the property 'MaxChunkedUploadParts'
        }
        /// <summary>
        /// Test the property 'MaxTotalSize'
        /// </summary>
        [Test]
        public void MaxTotalSizeTest()
        {
            // TODO unit test for the property 'MaxTotalSize'
        }
        /// <summary>
        /// Test the property 'TotalSize'
        /// </summary>
        [Test]
        public void TotalSizeTest()
        {
            // TODO unit test for the property 'TotalSize'
        }

    }

}
