/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing ConnectFailureResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConnectFailureResultTests
    {
        // TODO uncomment below to declare an instance variable for ConnectFailureResult
        //private ConnectFailureResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConnectFailureResult
            //instance = new ConnectFailureResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConnectFailureResult
        /// </summary>
        [Test]
        public void ConnectFailureResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConnectFailureResult
            //Assert.IsInstanceOfType<ConnectFailureResult> (instance, "variable 'instance' is a ConnectFailureResult");
        }

        /// <summary>
        /// Test the property 'ConfigId'
        /// </summary>
        [Test]
        public void ConfigIdTest()
        {
            // TODO unit test for the property 'ConfigId'
        }
        /// <summary>
        /// Test the property 'ConfigUrl'
        /// </summary>
        [Test]
        public void ConfigUrlTest()
        {
            // TODO unit test for the property 'ConfigUrl'
        }
        /// <summary>
        /// Test the property 'EnvelopeId'
        /// </summary>
        [Test]
        public void EnvelopeIdTest()
        {
            // TODO unit test for the property 'EnvelopeId'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'StatusMessage'
        /// </summary>
        [Test]
        public void StatusMessageTest()
        {
            // TODO unit test for the property 'StatusMessage'
        }

    }

}
