/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing ConnectLog
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConnectLogTests
    {
        // TODO uncomment below to declare an instance variable for ConnectLog
        //private ConnectLog instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConnectLog
            //instance = new ConnectLog();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConnectLog
        /// </summary>
        [Test]
        public void ConnectLogInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConnectLog
            //Assert.IsInstanceOfType<ConnectLog> (instance, "variable 'instance' is a ConnectLog");
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Test]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'ConfigUrl'
        /// </summary>
        [Test]
        public void ConfigUrlTest()
        {
            // TODO unit test for the property 'ConfigUrl'
        }
        /// <summary>
        /// Test the property 'ConnectDebugLog'
        /// </summary>
        [Test]
        public void ConnectDebugLogTest()
        {
            // TODO unit test for the property 'ConnectDebugLog'
        }
        /// <summary>
        /// Test the property 'ConnectId'
        /// </summary>
        [Test]
        public void ConnectIdTest()
        {
            // TODO unit test for the property 'ConnectId'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'EnvelopeId'
        /// </summary>
        [Test]
        public void EnvelopeIdTest()
        {
            // TODO unit test for the property 'EnvelopeId'
        }
        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Test]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
        /// <summary>
        /// Test the property 'FailureId'
        /// </summary>
        [Test]
        public void FailureIdTest()
        {
            // TODO unit test for the property 'FailureId'
        }
        /// <summary>
        /// Test the property 'FailureUri'
        /// </summary>
        [Test]
        public void FailureUriTest()
        {
            // TODO unit test for the property 'FailureUri'
        }
        /// <summary>
        /// Test the property 'LastTry'
        /// </summary>
        [Test]
        public void LastTryTest()
        {
            // TODO unit test for the property 'LastTry'
        }
        /// <summary>
        /// Test the property 'LogId'
        /// </summary>
        [Test]
        public void LogIdTest()
        {
            // TODO unit test for the property 'LogId'
        }
        /// <summary>
        /// Test the property 'LogUri'
        /// </summary>
        [Test]
        public void LogUriTest()
        {
            // TODO unit test for the property 'LogUri'
        }
        /// <summary>
        /// Test the property 'RetryCount'
        /// </summary>
        [Test]
        public void RetryCountTest()
        {
            // TODO unit test for the property 'RetryCount'
        }
        /// <summary>
        /// Test the property 'RetryUri'
        /// </summary>
        [Test]
        public void RetryUriTest()
        {
            // TODO unit test for the property 'RetryUri'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Test]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Test]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }

    }

}
