/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing ConnectDebugLog
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ConnectDebugLogTests
    {
        // TODO uncomment below to declare an instance variable for ConnectDebugLog
        //private ConnectDebugLog instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ConnectDebugLog
            //instance = new ConnectDebugLog();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ConnectDebugLog
        /// </summary>
        [Test]
        public void ConnectDebugLogInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ConnectDebugLog
            //Assert.IsInstanceOfType<ConnectDebugLog> (instance, "variable 'instance' is a ConnectDebugLog");
        }

        /// <summary>
        /// Test the property 'ConnectConfig'
        /// </summary>
        [Test]
        public void ConnectConfigTest()
        {
            // TODO unit test for the property 'ConnectConfig'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [Test]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'EventDateTime'
        /// </summary>
        [Test]
        public void EventDateTimeTest()
        {
            // TODO unit test for the property 'EventDateTime'
        }
        /// <summary>
        /// Test the property 'EventDescription'
        /// </summary>
        [Test]
        public void EventDescriptionTest()
        {
            // TODO unit test for the property 'EventDescription'
        }
        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Test]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }

    }

}
