/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing Contacts
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ContactsTests
    {
        // TODO uncomment below to declare an instance variable for Contacts
        //private Contacts instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Contacts
            //instance = new Contacts();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Contacts
        /// </summary>
        [Test]
        public void ContactsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Contacts
            //Assert.IsInstanceOfType<Contacts> (instance, "variable 'instance' is a Contacts");
        }

        /// <summary>
        /// Test the property 'ContactId'
        /// </summary>
        [Test]
        public void ContactIdTest()
        {
            // TODO unit test for the property 'ContactId'
        }
        /// <summary>
        /// Test the property 'ContactPhoneNumbers'
        /// </summary>
        [Test]
        public void ContactPhoneNumbersTest()
        {
            // TODO unit test for the property 'ContactPhoneNumbers'
        }
        /// <summary>
        /// Test the property 'ContactUri'
        /// </summary>
        [Test]
        public void ContactUriTest()
        {
            // TODO unit test for the property 'ContactUri'
        }
        /// <summary>
        /// Test the property 'Emails'
        /// </summary>
        [Test]
        public void EmailsTest()
        {
            // TODO unit test for the property 'Emails'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [Test]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Organization'
        /// </summary>
        [Test]
        public void OrganizationTest()
        {
            // TODO unit test for the property 'Organization'
        }
        /// <summary>
        /// Test the property 'Shared'
        /// </summary>
        [Test]
        public void SharedTest()
        {
            // TODO unit test for the property 'Shared'
        }
        /// <summary>
        /// Test the property 'SigningGroup'
        /// </summary>
        [Test]
        public void SigningGroupTest()
        {
            // TODO unit test for the property 'SigningGroup'
        }
        /// <summary>
        /// Test the property 'SigningGroupName'
        /// </summary>
        [Test]
        public void SigningGroupNameTest()
        {
            // TODO unit test for the property 'SigningGroupName'
        }

    }

}
