/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing CurrencyPlanPrice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CurrencyPlanPriceTests
    {
        // TODO uncomment below to declare an instance variable for CurrencyPlanPrice
        //private CurrencyPlanPrice instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CurrencyPlanPrice
            //instance = new CurrencyPlanPrice();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CurrencyPlanPrice
        /// </summary>
        [Test]
        public void CurrencyPlanPriceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CurrencyPlanPrice
            //Assert.IsInstanceOfType<CurrencyPlanPrice> (instance, "variable 'instance' is a CurrencyPlanPrice");
        }

        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Test]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }
        /// <summary>
        /// Test the property 'CurrencySymbol'
        /// </summary>
        [Test]
        public void CurrencySymbolTest()
        {
            // TODO unit test for the property 'CurrencySymbol'
        }
        /// <summary>
        /// Test the property 'PerSeatPrice'
        /// </summary>
        [Test]
        public void PerSeatPriceTest()
        {
            // TODO unit test for the property 'PerSeatPrice'
        }
        /// <summary>
        /// Test the property 'SupportedCardTypes'
        /// </summary>
        [Test]
        public void SupportedCardTypesTest()
        {
            // TODO unit test for the property 'SupportedCardTypes'
        }
        /// <summary>
        /// Test the property 'SupportIncidentFee'
        /// </summary>
        [Test]
        public void SupportIncidentFeeTest()
        {
            // TODO unit test for the property 'SupportIncidentFee'
        }
        /// <summary>
        /// Test the property 'SupportPlanFee'
        /// </summary>
        [Test]
        public void SupportPlanFeeTest()
        {
            // TODO unit test for the property 'SupportPlanFee'
        }

    }

}
