/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing DateStampProperties
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DateStampPropertiesTests
    {
        // TODO uncomment below to declare an instance variable for DateStampProperties
        //private DateStampProperties instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DateStampProperties
            //instance = new DateStampProperties();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DateStampProperties
        /// </summary>
        [Test]
        public void DateStampPropertiesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DateStampProperties
            //Assert.IsInstanceOfType<DateStampProperties> (instance, "variable 'instance' is a DateStampProperties");
        }

        /// <summary>
        /// Test the property 'DateAreaHeight'
        /// </summary>
        [Test]
        public void DateAreaHeightTest()
        {
            // TODO unit test for the property 'DateAreaHeight'
        }
        /// <summary>
        /// Test the property 'DateAreaWidth'
        /// </summary>
        [Test]
        public void DateAreaWidthTest()
        {
            // TODO unit test for the property 'DateAreaWidth'
        }
        /// <summary>
        /// Test the property 'DateAreaX'
        /// </summary>
        [Test]
        public void DateAreaXTest()
        {
            // TODO unit test for the property 'DateAreaX'
        }
        /// <summary>
        /// Test the property 'DateAreaY'
        /// </summary>
        [Test]
        public void DateAreaYTest()
        {
            // TODO unit test for the property 'DateAreaY'
        }

    }

}
