/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing EMortgageTransactions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EMortgageTransactionsTests
    {
        // TODO uncomment below to declare an instance variable for EMortgageTransactions
        //private EMortgageTransactions instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EMortgageTransactions
            //instance = new EMortgageTransactions();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EMortgageTransactions
        /// </summary>
        [Test]
        public void EMortgageTransactionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EMortgageTransactions
            //Assert.IsInstanceOfType<EMortgageTransactions> (instance, "variable 'instance' is a EMortgageTransactions");
        }

        /// <summary>
        /// Test the property 'DocumentData'
        /// </summary>
        [Test]
        public void DocumentDataTest()
        {
            // TODO unit test for the property 'DocumentData'
        }
        /// <summary>
        /// Test the property 'DptName'
        /// </summary>
        [Test]
        public void DptNameTest()
        {
            // TODO unit test for the property 'DptName'
        }
        /// <summary>
        /// Test the property 'TransactionName'
        /// </summary>
        [Test]
        public void TransactionNameTest()
        {
            // TODO unit test for the property 'TransactionName'
        }
        /// <summary>
        /// Test the property 'TransactionTypeName'
        /// </summary>
        [Test]
        public void TransactionTypeNameTest()
        {
            // TODO unit test for the property 'TransactionTypeName'
        }

    }

}
