/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing EnvelopeLocks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EnvelopeLocksTests
    {
        // TODO uncomment below to declare an instance variable for EnvelopeLocks
        //private EnvelopeLocks instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EnvelopeLocks
            //instance = new EnvelopeLocks();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EnvelopeLocks
        /// </summary>
        [Test]
        public void EnvelopeLocksInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EnvelopeLocks
            //Assert.IsInstanceOfType<EnvelopeLocks> (instance, "variable 'instance' is a EnvelopeLocks");
        }

        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [Test]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'LockDurationInSeconds'
        /// </summary>
        [Test]
        public void LockDurationInSecondsTest()
        {
            // TODO unit test for the property 'LockDurationInSeconds'
        }
        /// <summary>
        /// Test the property 'LockedByApp'
        /// </summary>
        [Test]
        public void LockedByAppTest()
        {
            // TODO unit test for the property 'LockedByApp'
        }
        /// <summary>
        /// Test the property 'LockedByUser'
        /// </summary>
        [Test]
        public void LockedByUserTest()
        {
            // TODO unit test for the property 'LockedByUser'
        }
        /// <summary>
        /// Test the property 'LockedUntilDateTime'
        /// </summary>
        [Test]
        public void LockedUntilDateTimeTest()
        {
            // TODO unit test for the property 'LockedUntilDateTime'
        }
        /// <summary>
        /// Test the property 'LockToken'
        /// </summary>
        [Test]
        public void LockTokenTest()
        {
            // TODO unit test for the property 'LockToken'
        }
        /// <summary>
        /// Test the property 'LockType'
        /// </summary>
        [Test]
        public void LockTypeTest()
        {
            // TODO unit test for the property 'LockType'
        }
        /// <summary>
        /// Test the property 'UseScratchPad'
        /// </summary>
        [Test]
        public void UseScratchPadTest()
        {
            // TODO unit test for the property 'UseScratchPad'
        }

    }

}
