/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing EnvelopeRecipients
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EnvelopeRecipientsTests
    {
        // TODO uncomment below to declare an instance variable for EnvelopeRecipients
        //private EnvelopeRecipients instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EnvelopeRecipients
            //instance = new EnvelopeRecipients();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EnvelopeRecipients
        /// </summary>
        [Test]
        public void EnvelopeRecipientsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EnvelopeRecipients
            //Assert.IsInstanceOfType<EnvelopeRecipients> (instance, "variable 'instance' is a EnvelopeRecipients");
        }

        /// <summary>
        /// Test the property 'Agents'
        /// </summary>
        [Test]
        public void AgentsTest()
        {
            // TODO unit test for the property 'Agents'
        }
        /// <summary>
        /// Test the property 'CarbonCopies'
        /// </summary>
        [Test]
        public void CarbonCopiesTest()
        {
            // TODO unit test for the property 'CarbonCopies'
        }
        /// <summary>
        /// Test the property 'CertifiedDeliveries'
        /// </summary>
        [Test]
        public void CertifiedDeliveriesTest()
        {
            // TODO unit test for the property 'CertifiedDeliveries'
        }
        /// <summary>
        /// Test the property 'CurrentRoutingOrder'
        /// </summary>
        [Test]
        public void CurrentRoutingOrderTest()
        {
            // TODO unit test for the property 'CurrentRoutingOrder'
        }
        /// <summary>
        /// Test the property 'Editors'
        /// </summary>
        [Test]
        public void EditorsTest()
        {
            // TODO unit test for the property 'Editors'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [Test]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'InPersonSigners'
        /// </summary>
        [Test]
        public void InPersonSignersTest()
        {
            // TODO unit test for the property 'InPersonSigners'
        }
        /// <summary>
        /// Test the property 'Intermediaries'
        /// </summary>
        [Test]
        public void IntermediariesTest()
        {
            // TODO unit test for the property 'Intermediaries'
        }
        /// <summary>
        /// Test the property 'RecipientCount'
        /// </summary>
        [Test]
        public void RecipientCountTest()
        {
            // TODO unit test for the property 'RecipientCount'
        }
        /// <summary>
        /// Test the property 'Signers'
        /// </summary>
        [Test]
        public void SignersTest()
        {
            // TODO unit test for the property 'Signers'
        }

    }

}
