/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing EventNotification
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class EventNotificationTests
    {
        // TODO uncomment below to declare an instance variable for EventNotification
        //private EventNotification instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of EventNotification
            //instance = new EventNotification();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of EventNotification
        /// </summary>
        [Test]
        public void EventNotificationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" EventNotification
            //Assert.IsInstanceOfType<EventNotification> (instance, "variable 'instance' is a EventNotification");
        }

        /// <summary>
        /// Test the property 'EnvelopeEvents'
        /// </summary>
        [Test]
        public void EnvelopeEventsTest()
        {
            // TODO unit test for the property 'EnvelopeEvents'
        }
        /// <summary>
        /// Test the property 'IncludeCertificateOfCompletion'
        /// </summary>
        [Test]
        public void IncludeCertificateOfCompletionTest()
        {
            // TODO unit test for the property 'IncludeCertificateOfCompletion'
        }
        /// <summary>
        /// Test the property 'IncludeCertificateWithSoap'
        /// </summary>
        [Test]
        public void IncludeCertificateWithSoapTest()
        {
            // TODO unit test for the property 'IncludeCertificateWithSoap'
        }
        /// <summary>
        /// Test the property 'IncludeDocumentFields'
        /// </summary>
        [Test]
        public void IncludeDocumentFieldsTest()
        {
            // TODO unit test for the property 'IncludeDocumentFields'
        }
        /// <summary>
        /// Test the property 'IncludeDocuments'
        /// </summary>
        [Test]
        public void IncludeDocumentsTest()
        {
            // TODO unit test for the property 'IncludeDocuments'
        }
        /// <summary>
        /// Test the property 'IncludeEnvelopeVoidReason'
        /// </summary>
        [Test]
        public void IncludeEnvelopeVoidReasonTest()
        {
            // TODO unit test for the property 'IncludeEnvelopeVoidReason'
        }
        /// <summary>
        /// Test the property 'IncludeSenderAccountAsCustomField'
        /// </summary>
        [Test]
        public void IncludeSenderAccountAsCustomFieldTest()
        {
            // TODO unit test for the property 'IncludeSenderAccountAsCustomField'
        }
        /// <summary>
        /// Test the property 'IncludeTimeZone'
        /// </summary>
        [Test]
        public void IncludeTimeZoneTest()
        {
            // TODO unit test for the property 'IncludeTimeZone'
        }
        /// <summary>
        /// Test the property 'LoggingEnabled'
        /// </summary>
        [Test]
        public void LoggingEnabledTest()
        {
            // TODO unit test for the property 'LoggingEnabled'
        }
        /// <summary>
        /// Test the property 'RecipientEvents'
        /// </summary>
        [Test]
        public void RecipientEventsTest()
        {
            // TODO unit test for the property 'RecipientEvents'
        }
        /// <summary>
        /// Test the property 'RequireAcknowledgment'
        /// </summary>
        [Test]
        public void RequireAcknowledgmentTest()
        {
            // TODO unit test for the property 'RequireAcknowledgment'
        }
        /// <summary>
        /// Test the property 'SignMessageWithX509Cert'
        /// </summary>
        [Test]
        public void SignMessageWithX509CertTest()
        {
            // TODO unit test for the property 'SignMessageWithX509Cert'
        }
        /// <summary>
        /// Test the property 'SoapNameSpace'
        /// </summary>
        [Test]
        public void SoapNameSpaceTest()
        {
            // TODO unit test for the property 'SoapNameSpace'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'UseSoapInterface'
        /// </summary>
        [Test]
        public void UseSoapInterfaceTest()
        {
            // TODO unit test for the property 'UseSoapInterface'
        }

    }

}
