/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing FeatureSet
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FeatureSetTests
    {
        // TODO uncomment below to declare an instance variable for FeatureSet
        //private FeatureSet instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FeatureSet
            //instance = new FeatureSet();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FeatureSet
        /// </summary>
        [Test]
        public void FeatureSetInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FeatureSet
            //Assert.IsInstanceOfType<FeatureSet> (instance, "variable 'instance' is a FeatureSet");
        }

        /// <summary>
        /// Test the property 'CurrencyFeatureSetPrices'
        /// </summary>
        [Test]
        public void CurrencyFeatureSetPricesTest()
        {
            // TODO unit test for the property 'CurrencyFeatureSetPrices'
        }
        /// <summary>
        /// Test the property 'EnvelopeFee'
        /// </summary>
        [Test]
        public void EnvelopeFeeTest()
        {
            // TODO unit test for the property 'EnvelopeFee'
        }
        /// <summary>
        /// Test the property 'FeatureSetId'
        /// </summary>
        [Test]
        public void FeatureSetIdTest()
        {
            // TODO unit test for the property 'FeatureSetId'
        }
        /// <summary>
        /// Test the property 'FixedFee'
        /// </summary>
        [Test]
        public void FixedFeeTest()
        {
            // TODO unit test for the property 'FixedFee'
        }
        /// <summary>
        /// Test the property 'Is21CFRPart11'
        /// </summary>
        [Test]
        public void Is21CFRPart11Test()
        {
            // TODO unit test for the property 'Is21CFRPart11'
        }
        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Test]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }
        /// <summary>
        /// Test the property 'IsEnabled'
        /// </summary>
        [Test]
        public void IsEnabledTest()
        {
            // TODO unit test for the property 'IsEnabled'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'SeatFee'
        /// </summary>
        [Test]
        public void SeatFeeTest()
        {
            // TODO unit test for the property 'SeatFee'
        }

    }

}
