/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing FolderItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FolderItemTests
    {
        // TODO uncomment below to declare an instance variable for FolderItem
        //private FolderItem instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FolderItem
            //instance = new FolderItem();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FolderItem
        /// </summary>
        [Test]
        public void FolderItemInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FolderItem
            //Assert.IsInstanceOfType<FolderItem> (instance, "variable 'instance' is a FolderItem");
        }

        /// <summary>
        /// Test the property 'CompletedDateTime'
        /// </summary>
        [Test]
        public void CompletedDateTimeTest()
        {
            // TODO unit test for the property 'CompletedDateTime'
        }
        /// <summary>
        /// Test the property 'CreatedDateTime'
        /// </summary>
        [Test]
        public void CreatedDateTimeTest()
        {
            // TODO unit test for the property 'CreatedDateTime'
        }
        /// <summary>
        /// Test the property 'CustomFields'
        /// </summary>
        [Test]
        public void CustomFieldsTest()
        {
            // TODO unit test for the property 'CustomFields'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'EnvelopeId'
        /// </summary>
        [Test]
        public void EnvelopeIdTest()
        {
            // TODO unit test for the property 'EnvelopeId'
        }
        /// <summary>
        /// Test the property 'EnvelopeUri'
        /// </summary>
        [Test]
        public void EnvelopeUriTest()
        {
            // TODO unit test for the property 'EnvelopeUri'
        }
        /// <summary>
        /// Test the property 'Is21CFRPart11'
        /// </summary>
        [Test]
        public void Is21CFRPart11Test()
        {
            // TODO unit test for the property 'Is21CFRPart11'
        }
        /// <summary>
        /// Test the property 'IsSignatureProviderEnvelope'
        /// </summary>
        [Test]
        public void IsSignatureProviderEnvelopeTest()
        {
            // TODO unit test for the property 'IsSignatureProviderEnvelope'
        }
        /// <summary>
        /// Test the property 'LastModified'
        /// </summary>
        [Test]
        public void LastModifiedTest()
        {
            // TODO unit test for the property 'LastModified'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'OwnerName'
        /// </summary>
        [Test]
        public void OwnerNameTest()
        {
            // TODO unit test for the property 'OwnerName'
        }
        /// <summary>
        /// Test the property 'PageCount'
        /// </summary>
        [Test]
        public void PageCountTest()
        {
            // TODO unit test for the property 'PageCount'
        }
        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Test]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
        /// <summary>
        /// Test the property 'SenderEmail'
        /// </summary>
        [Test]
        public void SenderEmailTest()
        {
            // TODO unit test for the property 'SenderEmail'
        }
        /// <summary>
        /// Test the property 'SenderName'
        /// </summary>
        [Test]
        public void SenderNameTest()
        {
            // TODO unit test for the property 'SenderName'
        }
        /// <summary>
        /// Test the property 'SentDateTime'
        /// </summary>
        [Test]
        public void SentDateTimeTest()
        {
            // TODO unit test for the property 'SentDateTime'
        }
        /// <summary>
        /// Test the property 'Shared'
        /// </summary>
        [Test]
        public void SharedTest()
        {
            // TODO unit test for the property 'Shared'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Test]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }
        /// <summary>
        /// Test the property 'TemplateId'
        /// </summary>
        [Test]
        public void TemplateIdTest()
        {
            // TODO unit test for the property 'TemplateId'
        }
        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }

    }

}
