/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing Invoices
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InvoicesTests
    {
        // TODO uncomment below to declare an instance variable for Invoices
        //private Invoices instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Invoices
            //instance = new Invoices();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Invoices
        /// </summary>
        [Test]
        public void InvoicesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Invoices
            //Assert.IsInstanceOfType<Invoices> (instance, "variable 'instance' is a Invoices");
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Test]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Test]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }
        /// <summary>
        /// Test the property 'DueDate'
        /// </summary>
        [Test]
        public void DueDateTest()
        {
            // TODO unit test for the property 'DueDate'
        }
        /// <summary>
        /// Test the property 'InvoiceId'
        /// </summary>
        [Test]
        public void InvoiceIdTest()
        {
            // TODO unit test for the property 'InvoiceId'
        }
        /// <summary>
        /// Test the property 'InvoiceItems'
        /// </summary>
        [Test]
        public void InvoiceItemsTest()
        {
            // TODO unit test for the property 'InvoiceItems'
        }
        /// <summary>
        /// Test the property 'InvoiceNumber'
        /// </summary>
        [Test]
        public void InvoiceNumberTest()
        {
            // TODO unit test for the property 'InvoiceNumber'
        }
        /// <summary>
        /// Test the property 'InvoiceUri'
        /// </summary>
        [Test]
        public void InvoiceUriTest()
        {
            // TODO unit test for the property 'InvoiceUri'
        }
        /// <summary>
        /// Test the property 'NonTaxableAmount'
        /// </summary>
        [Test]
        public void NonTaxableAmountTest()
        {
            // TODO unit test for the property 'NonTaxableAmount'
        }
        /// <summary>
        /// Test the property 'PdfAvailable'
        /// </summary>
        [Test]
        public void PdfAvailableTest()
        {
            // TODO unit test for the property 'PdfAvailable'
        }
        /// <summary>
        /// Test the property 'TaxableAmount'
        /// </summary>
        [Test]
        public void TaxableAmountTest()
        {
            // TODO unit test for the property 'TaxableAmount'
        }

    }

}
