/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing LoginAccount
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LoginAccountTests
    {
        // TODO uncomment below to declare an instance variable for LoginAccount
        //private LoginAccount instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LoginAccount
            //instance = new LoginAccount();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LoginAccount
        /// </summary>
        [Test]
        public void LoginAccountInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoginAccount
            //Assert.IsInstanceOfType<LoginAccount> (instance, "variable 'instance' is a LoginAccount");
        }

        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Test]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'AccountIdGuid'
        /// </summary>
        [Test]
        public void AccountIdGuidTest()
        {
            // TODO unit test for the property 'AccountIdGuid'
        }
        /// <summary>
        /// Test the property 'BaseUrl'
        /// </summary>
        [Test]
        public void BaseUrlTest()
        {
            // TODO unit test for the property 'BaseUrl'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'IsDefault'
        /// </summary>
        [Test]
        public void IsDefaultTest()
        {
            // TODO unit test for the property 'IsDefault'
        }
        /// <summary>
        /// Test the property 'LoginAccountSettings'
        /// </summary>
        [Test]
        public void LoginAccountSettingsTest()
        {
            // TODO unit test for the property 'LoginAccountSettings'
        }
        /// <summary>
        /// Test the property 'LoginUserSettings'
        /// </summary>
        [Test]
        public void LoginUserSettingsTest()
        {
            // TODO unit test for the property 'LoginUserSettings'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'SiteDescription'
        /// </summary>
        [Test]
        public void SiteDescriptionTest()
        {
            // TODO unit test for the property 'SiteDescription'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Test]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }

    }

}
