/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing NewAccountDefinition
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NewAccountDefinitionTests
    {
        // TODO uncomment below to declare an instance variable for NewAccountDefinition
        //private NewAccountDefinition instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NewAccountDefinition
            //instance = new NewAccountDefinition();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NewAccountDefinition
        /// </summary>
        [Test]
        public void NewAccountDefinitionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NewAccountDefinition
            //Assert.IsInstanceOfType<NewAccountDefinition> (instance, "variable 'instance' is a NewAccountDefinition");
        }

        /// <summary>
        /// Test the property 'AccountName'
        /// </summary>
        [Test]
        public void AccountNameTest()
        {
            // TODO unit test for the property 'AccountName'
        }
        /// <summary>
        /// Test the property 'AccountSettings'
        /// </summary>
        [Test]
        public void AccountSettingsTest()
        {
            // TODO unit test for the property 'AccountSettings'
        }
        /// <summary>
        /// Test the property 'AddressInformation'
        /// </summary>
        [Test]
        public void AddressInformationTest()
        {
            // TODO unit test for the property 'AddressInformation'
        }
        /// <summary>
        /// Test the property 'CreditCardInformation'
        /// </summary>
        [Test]
        public void CreditCardInformationTest()
        {
            // TODO unit test for the property 'CreditCardInformation'
        }
        /// <summary>
        /// Test the property 'DistributorCode'
        /// </summary>
        [Test]
        public void DistributorCodeTest()
        {
            // TODO unit test for the property 'DistributorCode'
        }
        /// <summary>
        /// Test the property 'DistributorPassword'
        /// </summary>
        [Test]
        public void DistributorPasswordTest()
        {
            // TODO unit test for the property 'DistributorPassword'
        }
        /// <summary>
        /// Test the property 'InitialUser'
        /// </summary>
        [Test]
        public void InitialUserTest()
        {
            // TODO unit test for the property 'InitialUser'
        }
        /// <summary>
        /// Test the property 'PaymentProcessorInformation'
        /// </summary>
        [Test]
        public void PaymentProcessorInformationTest()
        {
            // TODO unit test for the property 'PaymentProcessorInformation'
        }
        /// <summary>
        /// Test the property 'PlanInformation'
        /// </summary>
        [Test]
        public void PlanInformationTest()
        {
            // TODO unit test for the property 'PlanInformation'
        }
        /// <summary>
        /// Test the property 'ReferralInformation'
        /// </summary>
        [Test]
        public void ReferralInformationTest()
        {
            // TODO unit test for the property 'ReferralInformation'
        }
        /// <summary>
        /// Test the property 'SocialAccountInformation'
        /// </summary>
        [Test]
        public void SocialAccountInformationTest()
        {
            // TODO unit test for the property 'SocialAccountInformation'
        }

    }

}
