/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing NewUser
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class NewUserTests
    {
        // TODO uncomment below to declare an instance variable for NewUser
        //private NewUser instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of NewUser
            //instance = new NewUser();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of NewUser
        /// </summary>
        [Test]
        public void NewUserInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NewUser
            //Assert.IsInstanceOfType<NewUser> (instance, "variable 'instance' is a NewUser");
        }

        /// <summary>
        /// Test the property 'ApiPassword'
        /// </summary>
        [Test]
        public void ApiPasswordTest()
        {
            // TODO unit test for the property 'ApiPassword'
        }
        /// <summary>
        /// Test the property 'CreatedDateTime'
        /// </summary>
        [Test]
        public void CreatedDateTimeTest()
        {
            // TODO unit test for the property 'CreatedDateTime'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [Test]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'PermissionProfileId'
        /// </summary>
        [Test]
        public void PermissionProfileIdTest()
        {
            // TODO unit test for the property 'PermissionProfileId'
        }
        /// <summary>
        /// Test the property 'PermissionProfileName'
        /// </summary>
        [Test]
        public void PermissionProfileNameTest()
        {
            // TODO unit test for the property 'PermissionProfileName'
        }
        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Test]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }
        /// <summary>
        /// Test the property 'UserStatus'
        /// </summary>
        [Test]
        public void UserStatusTest()
        {
            // TODO unit test for the property 'UserStatus'
        }

    }

}
