/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing Page
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PageTests
    {
        // TODO uncomment below to declare an instance variable for Page
        //private Page instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Page
            //instance = new Page();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Page
        /// </summary>
        [Test]
        public void PageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Page
            //Assert.IsInstanceOfType<Page> (instance, "variable 'instance' is a Page");
        }

        /// <summary>
        /// Test the property 'Dpi'
        /// </summary>
        [Test]
        public void DpiTest()
        {
            // TODO unit test for the property 'Dpi'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [Test]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'Height'
        /// </summary>
        [Test]
        public void HeightTest()
        {
            // TODO unit test for the property 'Height'
        }
        /// <summary>
        /// Test the property 'ImageBytes'
        /// </summary>
        [Test]
        public void ImageBytesTest()
        {
            // TODO unit test for the property 'ImageBytes'
        }
        /// <summary>
        /// Test the property 'MimeType'
        /// </summary>
        [Test]
        public void MimeTypeTest()
        {
            // TODO unit test for the property 'MimeType'
        }
        /// <summary>
        /// Test the property 'PageId'
        /// </summary>
        [Test]
        public void PageIdTest()
        {
            // TODO unit test for the property 'PageId'
        }
        /// <summary>
        /// Test the property 'Sequence'
        /// </summary>
        [Test]
        public void SequenceTest()
        {
            // TODO unit test for the property 'Sequence'
        }
        /// <summary>
        /// Test the property 'Width'
        /// </summary>
        [Test]
        public void WidthTest()
        {
            // TODO unit test for the property 'Width'
        }

    }

}
