/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing PaymentGatewayAccounts
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PaymentGatewayAccountsTests
    {
        // TODO uncomment below to declare an instance variable for PaymentGatewayAccounts
        //private PaymentGatewayAccounts instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PaymentGatewayAccounts
            //instance = new PaymentGatewayAccounts();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PaymentGatewayAccounts
        /// </summary>
        [Test]
        public void PaymentGatewayAccountsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PaymentGatewayAccounts
            //Assert.IsInstanceOfType<PaymentGatewayAccounts> (instance, "variable 'instance' is a PaymentGatewayAccounts");
        }

        /// <summary>
        /// Test the property 'DisplayName'
        /// </summary>
        [Test]
        public void DisplayNameTest()
        {
            // TODO unit test for the property 'DisplayName'
        }
        /// <summary>
        /// Test the property 'PaymentGateway'
        /// </summary>
        [Test]
        public void PaymentGatewayTest()
        {
            // TODO unit test for the property 'PaymentGateway'
        }
        /// <summary>
        /// Test the property 'PaymentGatewayAccountId'
        /// </summary>
        [Test]
        public void PaymentGatewayAccountIdTest()
        {
            // TODO unit test for the property 'PaymentGatewayAccountId'
        }

    }

}
