/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing PowerFormRecipient
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PowerFormRecipientTests
    {
        // TODO uncomment below to declare an instance variable for PowerFormRecipient
        //private PowerFormRecipient instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PowerFormRecipient
            //instance = new PowerFormRecipient();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PowerFormRecipient
        /// </summary>
        [Test]
        public void PowerFormRecipientInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PowerFormRecipient
            //Assert.IsInstanceOfType<PowerFormRecipient> (instance, "variable 'instance' is a PowerFormRecipient");
        }

        /// <summary>
        /// Test the property 'AccessCode'
        /// </summary>
        [Test]
        public void AccessCodeTest()
        {
            // TODO unit test for the property 'AccessCode'
        }
        /// <summary>
        /// Test the property 'AccessCodeLocked'
        /// </summary>
        [Test]
        public void AccessCodeLockedTest()
        {
            // TODO unit test for the property 'AccessCodeLocked'
        }
        /// <summary>
        /// Test the property 'AccessCodeRequired'
        /// </summary>
        [Test]
        public void AccessCodeRequiredTest()
        {
            // TODO unit test for the property 'AccessCodeRequired'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'EmailLocked'
        /// </summary>
        [Test]
        public void EmailLockedTest()
        {
            // TODO unit test for the property 'EmailLocked'
        }
        /// <summary>
        /// Test the property 'IdCheckConfigurationName'
        /// </summary>
        [Test]
        public void IdCheckConfigurationNameTest()
        {
            // TODO unit test for the property 'IdCheckConfigurationName'
        }
        /// <summary>
        /// Test the property 'IdCheckRequired'
        /// </summary>
        [Test]
        public void IdCheckRequiredTest()
        {
            // TODO unit test for the property 'IdCheckRequired'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'RecipientType'
        /// </summary>
        [Test]
        public void RecipientTypeTest()
        {
            // TODO unit test for the property 'RecipientType'
        }
        /// <summary>
        /// Test the property 'RoleName'
        /// </summary>
        [Test]
        public void RoleNameTest()
        {
            // TODO unit test for the property 'RoleName'
        }
        /// <summary>
        /// Test the property 'RoutingOrder'
        /// </summary>
        [Test]
        public void RoutingOrderTest()
        {
            // TODO unit test for the property 'RoutingOrder'
        }
        /// <summary>
        /// Test the property 'TemplateRequiresIdLookup'
        /// </summary>
        [Test]
        public void TemplateRequiresIdLookupTest()
        {
            // TODO unit test for the property 'TemplateRequiresIdLookup'
        }
        /// <summary>
        /// Test the property 'UserNameLocked'
        /// </summary>
        [Test]
        public void UserNameLockedTest()
        {
            // TODO unit test for the property 'UserNameLocked'
        }

    }

}
