/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing ProvisioningInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ProvisioningInformationTests
    {
        // TODO uncomment below to declare an instance variable for ProvisioningInformation
        //private ProvisioningInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ProvisioningInformation
            //instance = new ProvisioningInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ProvisioningInformation
        /// </summary>
        [Test]
        public void ProvisioningInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ProvisioningInformation
            //Assert.IsInstanceOfType<ProvisioningInformation> (instance, "variable 'instance' is a ProvisioningInformation");
        }

        /// <summary>
        /// Test the property 'DefaultConnectionId'
        /// </summary>
        [Test]
        public void DefaultConnectionIdTest()
        {
            // TODO unit test for the property 'DefaultConnectionId'
        }
        /// <summary>
        /// Test the property 'DefaultPlanId'
        /// </summary>
        [Test]
        public void DefaultPlanIdTest()
        {
            // TODO unit test for the property 'DefaultPlanId'
        }
        /// <summary>
        /// Test the property 'DistributorCode'
        /// </summary>
        [Test]
        public void DistributorCodeTest()
        {
            // TODO unit test for the property 'DistributorCode'
        }
        /// <summary>
        /// Test the property 'DistributorPassword'
        /// </summary>
        [Test]
        public void DistributorPasswordTest()
        {
            // TODO unit test for the property 'DistributorPassword'
        }
        /// <summary>
        /// Test the property 'PasswordRuleText'
        /// </summary>
        [Test]
        public void PasswordRuleTextTest()
        {
            // TODO unit test for the property 'PasswordRuleText'
        }
        /// <summary>
        /// Test the property 'PlanPromotionText'
        /// </summary>
        [Test]
        public void PlanPromotionTextTest()
        {
            // TODO unit test for the property 'PlanPromotionText'
        }
        /// <summary>
        /// Test the property 'PurchaseOrderOrPromAllowed'
        /// </summary>
        [Test]
        public void PurchaseOrderOrPromAllowedTest()
        {
            // TODO unit test for the property 'PurchaseOrderOrPromAllowed'
        }

    }

}
