/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing RadioGroup
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RadioGroupTests
    {
        // TODO uncomment below to declare an instance variable for RadioGroup
        //private RadioGroup instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RadioGroup
            //instance = new RadioGroup();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RadioGroup
        /// </summary>
        [Test]
        public void RadioGroupInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RadioGroup
            //Assert.IsInstanceOfType<RadioGroup> (instance, "variable 'instance' is a RadioGroup");
        }

        /// <summary>
        /// Test the property 'ConditionalParentLabel'
        /// </summary>
        [Test]
        public void ConditionalParentLabelTest()
        {
            // TODO unit test for the property 'ConditionalParentLabel'
        }
        /// <summary>
        /// Test the property 'ConditionalParentValue'
        /// </summary>
        [Test]
        public void ConditionalParentValueTest()
        {
            // TODO unit test for the property 'ConditionalParentValue'
        }
        /// <summary>
        /// Test the property 'DocumentId'
        /// </summary>
        [Test]
        public void DocumentIdTest()
        {
            // TODO unit test for the property 'DocumentId'
        }
        /// <summary>
        /// Test the property 'GroupName'
        /// </summary>
        [Test]
        public void GroupNameTest()
        {
            // TODO unit test for the property 'GroupName'
        }
        /// <summary>
        /// Test the property 'Radios'
        /// </summary>
        [Test]
        public void RadiosTest()
        {
            // TODO unit test for the property 'Radios'
        }
        /// <summary>
        /// Test the property 'RecipientId'
        /// </summary>
        [Test]
        public void RecipientIdTest()
        {
            // TODO unit test for the property 'RecipientId'
        }
        /// <summary>
        /// Test the property 'RequireAll'
        /// </summary>
        [Test]
        public void RequireAllTest()
        {
            // TODO unit test for the property 'RequireAll'
        }
        /// <summary>
        /// Test the property 'RequireInitialOnSharedChange'
        /// </summary>
        [Test]
        public void RequireInitialOnSharedChangeTest()
        {
            // TODO unit test for the property 'RequireInitialOnSharedChange'
        }
        /// <summary>
        /// Test the property 'Shared'
        /// </summary>
        [Test]
        public void SharedTest()
        {
            // TODO unit test for the property 'Shared'
        }

    }

}
