/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing RecipientViewRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RecipientViewRequestTests
    {
        // TODO uncomment below to declare an instance variable for RecipientViewRequest
        //private RecipientViewRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RecipientViewRequest
            //instance = new RecipientViewRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RecipientViewRequest
        /// </summary>
        [Test]
        public void RecipientViewRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RecipientViewRequest
            //Assert.IsInstanceOfType<RecipientViewRequest> (instance, "variable 'instance' is a RecipientViewRequest");
        }

        /// <summary>
        /// Test the property 'AssertionId'
        /// </summary>
        [Test]
        public void AssertionIdTest()
        {
            // TODO unit test for the property 'AssertionId'
        }
        /// <summary>
        /// Test the property 'AuthenticationInstant'
        /// </summary>
        [Test]
        public void AuthenticationInstantTest()
        {
            // TODO unit test for the property 'AuthenticationInstant'
        }
        /// <summary>
        /// Test the property 'AuthenticationMethod'
        /// </summary>
        [Test]
        public void AuthenticationMethodTest()
        {
            // TODO unit test for the property 'AuthenticationMethod'
        }
        /// <summary>
        /// Test the property 'ClientUserId'
        /// </summary>
        [Test]
        public void ClientUserIdTest()
        {
            // TODO unit test for the property 'ClientUserId'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'PingFrequency'
        /// </summary>
        [Test]
        public void PingFrequencyTest()
        {
            // TODO unit test for the property 'PingFrequency'
        }
        /// <summary>
        /// Test the property 'PingUrl'
        /// </summary>
        [Test]
        public void PingUrlTest()
        {
            // TODO unit test for the property 'PingUrl'
        }
        /// <summary>
        /// Test the property 'RecipientId'
        /// </summary>
        [Test]
        public void RecipientIdTest()
        {
            // TODO unit test for the property 'RecipientId'
        }
        /// <summary>
        /// Test the property 'ReturnUrl'
        /// </summary>
        [Test]
        public void ReturnUrlTest()
        {
            // TODO unit test for the property 'ReturnUrl'
        }
        /// <summary>
        /// Test the property 'SecurityDomain'
        /// </summary>
        [Test]
        public void SecurityDomainTest()
        {
            // TODO unit test for the property 'SecurityDomain'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Test]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Test]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }
        /// <summary>
        /// Test the property 'XFrameOptions'
        /// </summary>
        [Test]
        public void XFrameOptionsTest()
        {
            // TODO unit test for the property 'XFrameOptions'
        }
        /// <summary>
        /// Test the property 'XFrameOptionsAllowFromUrl'
        /// </summary>
        [Test]
        public void XFrameOptionsAllowFromUrlTest()
        {
            // TODO unit test for the property 'XFrameOptionsAllowFromUrl'
        }

    }

}
