/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing RecipientFormData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RecipientFormDataTests
    {
        // TODO uncomment below to declare an instance variable for RecipientFormData
        //private RecipientFormData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RecipientFormData
            //instance = new RecipientFormData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RecipientFormData
        /// </summary>
        [Test]
        public void RecipientFormDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RecipientFormData
            //Assert.IsInstanceOfType<RecipientFormData> (instance, "variable 'instance' is a RecipientFormData");
        }

        /// <summary>
        /// Test the property 'DeclinedTime'
        /// </summary>
        [Test]
        public void DeclinedTimeTest()
        {
            // TODO unit test for the property 'DeclinedTime'
        }
        /// <summary>
        /// Test the property 'DeliveredTime'
        /// </summary>
        [Test]
        public void DeliveredTimeTest()
        {
            // TODO unit test for the property 'DeliveredTime'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'FormData'
        /// </summary>
        [Test]
        public void FormDataTest()
        {
            // TODO unit test for the property 'FormData'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'RecipientId'
        /// </summary>
        [Test]
        public void RecipientIdTest()
        {
            // TODO unit test for the property 'RecipientId'
        }
        /// <summary>
        /// Test the property 'SentTime'
        /// </summary>
        [Test]
        public void SentTimeTest()
        {
            // TODO unit test for the property 'SentTime'
        }
        /// <summary>
        /// Test the property 'SignedTime'
        /// </summary>
        [Test]
        public void SignedTimeTest()
        {
            // TODO unit test for the property 'SignedTime'
        }

    }

}
