/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing RecipientAttachment
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RecipientAttachmentTests
    {
        // TODO uncomment below to declare an instance variable for RecipientAttachment
        //private RecipientAttachment instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RecipientAttachment
            //instance = new RecipientAttachment();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RecipientAttachment
        /// </summary>
        [Test]
        public void RecipientAttachmentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RecipientAttachment
            //Assert.IsInstanceOfType<RecipientAttachment> (instance, "variable 'instance' is a RecipientAttachment");
        }

        /// <summary>
        /// Test the property 'AttachmentId'
        /// </summary>
        [Test]
        public void AttachmentIdTest()
        {
            // TODO unit test for the property 'AttachmentId'
        }
        /// <summary>
        /// Test the property 'AttachmentType'
        /// </summary>
        [Test]
        public void AttachmentTypeTest()
        {
            // TODO unit test for the property 'AttachmentType'
        }
        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Test]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'RemoteUrl'
        /// </summary>
        [Test]
        public void RemoteUrlTest()
        {
            // TODO unit test for the property 'RemoteUrl'
        }

    }

}
