/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing SenderEmailNotifications
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SenderEmailNotificationsTests
    {
        // TODO uncomment below to declare an instance variable for SenderEmailNotifications
        //private SenderEmailNotifications instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SenderEmailNotifications
            //instance = new SenderEmailNotifications();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SenderEmailNotifications
        /// </summary>
        [Test]
        public void SenderEmailNotificationsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SenderEmailNotifications
            //Assert.IsInstanceOfType<SenderEmailNotifications> (instance, "variable 'instance' is a SenderEmailNotifications");
        }

        /// <summary>
        /// Test the property 'ChangedSigner'
        /// </summary>
        [Test]
        public void ChangedSignerTest()
        {
            // TODO unit test for the property 'ChangedSigner'
        }
        /// <summary>
        /// Test the property 'DeliveryFailed'
        /// </summary>
        [Test]
        public void DeliveryFailedTest()
        {
            // TODO unit test for the property 'DeliveryFailed'
        }
        /// <summary>
        /// Test the property 'EnvelopeComplete'
        /// </summary>
        [Test]
        public void EnvelopeCompleteTest()
        {
            // TODO unit test for the property 'EnvelopeComplete'
        }
        /// <summary>
        /// Test the property 'OfflineSigningFailed'
        /// </summary>
        [Test]
        public void OfflineSigningFailedTest()
        {
            // TODO unit test for the property 'OfflineSigningFailed'
        }
        /// <summary>
        /// Test the property 'RecipientViewed'
        /// </summary>
        [Test]
        public void RecipientViewedTest()
        {
            // TODO unit test for the property 'RecipientViewed'
        }
        /// <summary>
        /// Test the property 'SenderEnvelopeDeclined'
        /// </summary>
        [Test]
        public void SenderEnvelopeDeclinedTest()
        {
            // TODO unit test for the property 'SenderEnvelopeDeclined'
        }
        /// <summary>
        /// Test the property 'WithdrawnConsent'
        /// </summary>
        [Test]
        public void WithdrawnConsentTest()
        {
            // TODO unit test for the property 'WithdrawnConsent'
        }

    }

}
