/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing UserSignatures
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserSignaturesTests
    {
        // TODO uncomment below to declare an instance variable for UserSignatures
        //private UserSignatures instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserSignatures
            //instance = new UserSignatures();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserSignatures
        /// </summary>
        [Test]
        public void UserSignaturesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserSignatures
            //Assert.IsInstanceOfType<UserSignatures> (instance, "variable 'instance' is a UserSignatures");
        }

        /// <summary>
        /// Test the property 'AdoptedDateTime'
        /// </summary>
        [Test]
        public void AdoptedDateTimeTest()
        {
            // TODO unit test for the property 'AdoptedDateTime'
        }
        /// <summary>
        /// Test the property 'CreatedDateTime'
        /// </summary>
        [Test]
        public void CreatedDateTimeTest()
        {
            // TODO unit test for the property 'CreatedDateTime'
        }
        /// <summary>
        /// Test the property 'DateStampProperties'
        /// </summary>
        [Test]
        public void DateStampPropertiesTest()
        {
            // TODO unit test for the property 'DateStampProperties'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [Test]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'ExternalID'
        /// </summary>
        [Test]
        public void ExternalIDTest()
        {
            // TODO unit test for the property 'ExternalID'
        }
        /// <summary>
        /// Test the property 'ImageType'
        /// </summary>
        [Test]
        public void ImageTypeTest()
        {
            // TODO unit test for the property 'ImageType'
        }
        /// <summary>
        /// Test the property 'Initials150ImageId'
        /// </summary>
        [Test]
        public void Initials150ImageIdTest()
        {
            // TODO unit test for the property 'Initials150ImageId'
        }
        /// <summary>
        /// Test the property 'InitialsImageUri'
        /// </summary>
        [Test]
        public void InitialsImageUriTest()
        {
            // TODO unit test for the property 'InitialsImageUri'
        }
        /// <summary>
        /// Test the property 'IsDefault'
        /// </summary>
        [Test]
        public void IsDefaultTest()
        {
            // TODO unit test for the property 'IsDefault'
        }
        /// <summary>
        /// Test the property 'PhoneticName'
        /// </summary>
        [Test]
        public void PhoneticNameTest()
        {
            // TODO unit test for the property 'PhoneticName'
        }
        /// <summary>
        /// Test the property 'Signature150ImageId'
        /// </summary>
        [Test]
        public void Signature150ImageIdTest()
        {
            // TODO unit test for the property 'Signature150ImageId'
        }
        /// <summary>
        /// Test the property 'SignatureFont'
        /// </summary>
        [Test]
        public void SignatureFontTest()
        {
            // TODO unit test for the property 'SignatureFont'
        }
        /// <summary>
        /// Test the property 'SignatureId'
        /// </summary>
        [Test]
        public void SignatureIdTest()
        {
            // TODO unit test for the property 'SignatureId'
        }
        /// <summary>
        /// Test the property 'SignatureImageUri'
        /// </summary>
        [Test]
        public void SignatureImageUriTest()
        {
            // TODO unit test for the property 'SignatureImageUri'
        }
        /// <summary>
        /// Test the property 'SignatureInitials'
        /// </summary>
        [Test]
        public void SignatureInitialsTest()
        {
            // TODO unit test for the property 'SignatureInitials'
        }
        /// <summary>
        /// Test the property 'SignatureName'
        /// </summary>
        [Test]
        public void SignatureNameTest()
        {
            // TODO unit test for the property 'SignatureName'
        }
        /// <summary>
        /// Test the property 'SignatureType'
        /// </summary>
        [Test]
        public void SignatureTypeTest()
        {
            // TODO unit test for the property 'SignatureType'
        }
        /// <summary>
        /// Test the property 'StampFormat'
        /// </summary>
        [Test]
        public void StampFormatTest()
        {
            // TODO unit test for the property 'StampFormat'
        }
        /// <summary>
        /// Test the property 'StampImageUri'
        /// </summary>
        [Test]
        public void StampImageUriTest()
        {
            // TODO unit test for the property 'StampImageUri'
        }
        /// <summary>
        /// Test the property 'StampSizeMM'
        /// </summary>
        [Test]
        public void StampSizeMMTest()
        {
            // TODO unit test for the property 'StampSizeMM'
        }
        /// <summary>
        /// Test the property 'StampType'
        /// </summary>
        [Test]
        public void StampTypeTest()
        {
            // TODO unit test for the property 'StampType'
        }

    }

}
