/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing UserProfiles
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserProfilesTests
    {
        // TODO uncomment below to declare an instance variable for UserProfiles
        //private UserProfiles instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserProfiles
            //instance = new UserProfiles();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserProfiles
        /// </summary>
        [Test]
        public void UserProfilesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserProfiles
            //Assert.IsInstanceOfType<UserProfiles> (instance, "variable 'instance' is a UserProfiles");
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'AuthenticationMethods'
        /// </summary>
        [Test]
        public void AuthenticationMethodsTest()
        {
            // TODO unit test for the property 'AuthenticationMethods'
        }
        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Test]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'DisplayOrganizationInfo'
        /// </summary>
        [Test]
        public void DisplayOrganizationInfoTest()
        {
            // TODO unit test for the property 'DisplayOrganizationInfo'
        }
        /// <summary>
        /// Test the property 'DisplayPersonalInfo'
        /// </summary>
        [Test]
        public void DisplayPersonalInfoTest()
        {
            // TODO unit test for the property 'DisplayPersonalInfo'
        }
        /// <summary>
        /// Test the property 'DisplayProfile'
        /// </summary>
        [Test]
        public void DisplayProfileTest()
        {
            // TODO unit test for the property 'DisplayProfile'
        }
        /// <summary>
        /// Test the property 'DisplayUsageHistory'
        /// </summary>
        [Test]
        public void DisplayUsageHistoryTest()
        {
            // TODO unit test for the property 'DisplayUsageHistory'
        }
        /// <summary>
        /// Test the property 'ProfileImageUri'
        /// </summary>
        [Test]
        public void ProfileImageUriTest()
        {
            // TODO unit test for the property 'ProfileImageUri'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'UsageHistory'
        /// </summary>
        [Test]
        public void UsageHistoryTest()
        {
            // TODO unit test for the property 'UsageHistory'
        }
        /// <summary>
        /// Test the property 'UserDetails'
        /// </summary>
        [Test]
        public void UserDetailsTest()
        {
            // TODO unit test for the property 'UserDetails'
        }
        /// <summary>
        /// Test the property 'UserProfileLastModifiedDate'
        /// </summary>
        [Test]
        public void UserProfileLastModifiedDateTest()
        {
            // TODO unit test for the property 'UserProfileLastModifiedDate'
        }

    }

}
