/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing UserAccountManagementGranularInformation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class UserAccountManagementGranularInformationTests
    {
        // TODO uncomment below to declare an instance variable for UserAccountManagementGranularInformation
        //private UserAccountManagementGranularInformation instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of UserAccountManagementGranularInformation
            //instance = new UserAccountManagementGranularInformation();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of UserAccountManagementGranularInformation
        /// </summary>
        [Test]
        public void UserAccountManagementGranularInformationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" UserAccountManagementGranularInformation
            //Assert.IsInstanceOfType<UserAccountManagementGranularInformation> (instance, "variable 'instance' is a UserAccountManagementGranularInformation");
        }

        /// <summary>
        /// Test the property 'CanManageAdmins'
        /// </summary>
        [Test]
        public void CanManageAdminsTest()
        {
            // TODO unit test for the property 'CanManageAdmins'
        }
        /// <summary>
        /// Test the property 'CanManageAdminsMetadata'
        /// </summary>
        [Test]
        public void CanManageAdminsMetadataTest()
        {
            // TODO unit test for the property 'CanManageAdminsMetadata'
        }
        /// <summary>
        /// Test the property 'CanManageGroups'
        /// </summary>
        [Test]
        public void CanManageGroupsTest()
        {
            // TODO unit test for the property 'CanManageGroups'
        }
        /// <summary>
        /// Test the property 'CanManageGroupsMetadata'
        /// </summary>
        [Test]
        public void CanManageGroupsMetadataTest()
        {
            // TODO unit test for the property 'CanManageGroupsMetadata'
        }
        /// <summary>
        /// Test the property 'CanManageSharing'
        /// </summary>
        [Test]
        public void CanManageSharingTest()
        {
            // TODO unit test for the property 'CanManageSharing'
        }
        /// <summary>
        /// Test the property 'CanManageSharingMetadata'
        /// </summary>
        [Test]
        public void CanManageSharingMetadataTest()
        {
            // TODO unit test for the property 'CanManageSharingMetadata'
        }
        /// <summary>
        /// Test the property 'CanManageUsers'
        /// </summary>
        [Test]
        public void CanManageUsersTest()
        {
            // TODO unit test for the property 'CanManageUsers'
        }
        /// <summary>
        /// Test the property 'CanManageUsersMetadata'
        /// </summary>
        [Test]
        public void CanManageUsersMetadataTest()
        {
            // TODO unit test for the property 'CanManageUsersMetadata'
        }

    }

}
