/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing WorkspaceUserAuthorization
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WorkspaceUserAuthorizationTests
    {
        // TODO uncomment below to declare an instance variable for WorkspaceUserAuthorization
        //private WorkspaceUserAuthorization instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WorkspaceUserAuthorization
            //instance = new WorkspaceUserAuthorization();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WorkspaceUserAuthorization
        /// </summary>
        [Test]
        public void WorkspaceUserAuthorizationInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WorkspaceUserAuthorization
            //Assert.IsInstanceOfType<WorkspaceUserAuthorization> (instance, "variable 'instance' is a WorkspaceUserAuthorization");
        }

        /// <summary>
        /// Test the property 'CanDelete'
        /// </summary>
        [Test]
        public void CanDeleteTest()
        {
            // TODO unit test for the property 'CanDelete'
        }
        /// <summary>
        /// Test the property 'CanMove'
        /// </summary>
        [Test]
        public void CanMoveTest()
        {
            // TODO unit test for the property 'CanMove'
        }
        /// <summary>
        /// Test the property 'CanTransact'
        /// </summary>
        [Test]
        public void CanTransactTest()
        {
            // TODO unit test for the property 'CanTransact'
        }
        /// <summary>
        /// Test the property 'CanView'
        /// </summary>
        [Test]
        public void CanViewTest()
        {
            // TODO unit test for the property 'CanView'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'CreatedById'
        /// </summary>
        [Test]
        public void CreatedByIdTest()
        {
            // TODO unit test for the property 'CreatedById'
        }
        /// <summary>
        /// Test the property 'ErrorDetails'
        /// </summary>
        [Test]
        public void ErrorDetailsTest()
        {
            // TODO unit test for the property 'ErrorDetails'
        }
        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Test]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }
        /// <summary>
        /// Test the property 'ModifiedById'
        /// </summary>
        [Test]
        public void ModifiedByIdTest()
        {
            // TODO unit test for the property 'ModifiedById'
        }
        /// <summary>
        /// Test the property 'WorkspaceUserId'
        /// </summary>
        [Test]
        public void WorkspaceUserIdTest()
        {
            // TODO unit test for the property 'WorkspaceUserId'
        }
        /// <summary>
        /// Test the property 'WorkspaceUserInformation'
        /// </summary>
        [Test]
        public void WorkspaceUserInformationTest()
        {
            // TODO unit test for the property 'WorkspaceUserInformation'
        }

    }

}
