/* 
 * DocuSign REST API
 *
 * The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
 *
 * OpenAPI spec version: v2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

namespace DocuSign.eSign.Test.Model
{
    /// <summary>
    ///  Class for testing WorkspaceItems
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class WorkspaceItemsTests
    {
        // TODO uncomment below to declare an instance variable for WorkspaceItems
        //private WorkspaceItems instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of WorkspaceItems
            //instance = new WorkspaceItems();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of WorkspaceItems
        /// </summary>
        [Test]
        public void WorkspaceItemsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" WorkspaceItems
            //Assert.IsInstanceOfType<WorkspaceItems> (instance, "variable 'instance' is a WorkspaceItems");
        }

        /// <summary>
        /// Test the property 'CallerAuthorization'
        /// </summary>
        [Test]
        public void CallerAuthorizationTest()
        {
            // TODO unit test for the property 'CallerAuthorization'
        }
        /// <summary>
        /// Test the property 'ContentType'
        /// </summary>
        [Test]
        public void ContentTypeTest()
        {
            // TODO unit test for the property 'ContentType'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Test]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'CreatedById'
        /// </summary>
        [Test]
        public void CreatedByIdTest()
        {
            // TODO unit test for the property 'CreatedById'
        }
        /// <summary>
        /// Test the property 'CreatedByInformation'
        /// </summary>
        [Test]
        public void CreatedByInformationTest()
        {
            // TODO unit test for the property 'CreatedByInformation'
        }
        /// <summary>
        /// Test the property 'Extension'
        /// </summary>
        [Test]
        public void ExtensionTest()
        {
            // TODO unit test for the property 'Extension'
        }
        /// <summary>
        /// Test the property 'FileSize'
        /// </summary>
        [Test]
        public void FileSizeTest()
        {
            // TODO unit test for the property 'FileSize'
        }
        /// <summary>
        /// Test the property 'FileUri'
        /// </summary>
        [Test]
        public void FileUriTest()
        {
            // TODO unit test for the property 'FileUri'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'IsPublic'
        /// </summary>
        [Test]
        public void IsPublicTest()
        {
            // TODO unit test for the property 'IsPublic'
        }
        /// <summary>
        /// Test the property 'LastModified'
        /// </summary>
        [Test]
        public void LastModifiedTest()
        {
            // TODO unit test for the property 'LastModified'
        }
        /// <summary>
        /// Test the property 'LastModifiedById'
        /// </summary>
        [Test]
        public void LastModifiedByIdTest()
        {
            // TODO unit test for the property 'LastModifiedById'
        }
        /// <summary>
        /// Test the property 'LastModifiedByInformation'
        /// </summary>
        [Test]
        public void LastModifiedByInformationTest()
        {
            // TODO unit test for the property 'LastModifiedByInformation'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'PageCount'
        /// </summary>
        [Test]
        public void PageCountTest()
        {
            // TODO unit test for the property 'PageCount'
        }
        /// <summary>
        /// Test the property 'ParentFolderId'
        /// </summary>
        [Test]
        public void ParentFolderIdTest()
        {
            // TODO unit test for the property 'ParentFolderId'
        }
        /// <summary>
        /// Test the property 'ParentFolderUri'
        /// </summary>
        [Test]
        public void ParentFolderUriTest()
        {
            // TODO unit test for the property 'ParentFolderUri'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Uri'
        /// </summary>
        [Test]
        public void UriTest()
        {
            // TODO unit test for the property 'Uri'
        }

    }

}
